return {
	{ word = "\\wj.", label = "\\wj.  ⁠", insertText = "⁠", filterText = "\\wj." },
	{ word = "\\zwj.", label = "\\zwj.  ‍", insertText = "‍", filterText = "\\zwj." },
	{ word = "\\zwnj.", label = "\\zwnj.  ‌", insertText = "‌", filterText = "\\zwnj." },
	{ word = "\\zws.", label = "\\zws.  ​", insertText = "​", filterText = "\\zws." },
	{ word = "\\lrm.", label = "\\lrm.  ‎", insertText = "‎", filterText = "\\lrm." },
	{ word = "\\rlm.", label = "\\rlm.  ‏", insertText = "‏", filterText = "\\rlm." },
	{ word = "\\space.", label = "\\space.   ", insertText = " ", filterText = "\\space." },
	{ word = "\\space.nobreak", label = "\\space.nobreak   ", insertText = " ", filterText = "\\space.nobreak" },
	{
		word = "\\space.nobreak.narrow",
		label = "\\space.nobreak.narrow   ",
		insertText = " ",
		filterText = "\\space.nobreak.narrow",
	},
	{ word = "\\space.en", label = "\\space.en   ", insertText = " ", filterText = "\\space.en" },
	{ word = "\\space.quad", label = "\\space.quad   ", insertText = " ", filterText = "\\space.quad" },
	{ word = "\\space.third", label = "\\space.third   ", insertText = " ", filterText = "\\space.third" },
	{ word = "\\space.quarter", label = "\\space.quarter   ", insertText = " ", filterText = "\\space.quarter" },
	{ word = "\\space.sixth", label = "\\space.sixth   ", insertText = " ", filterText = "\\space.sixth" },
	{ word = "\\space.med", label = "\\space.med   ", insertText = " ", filterText = "\\space.med" },
	{ word = "\\space.fig", label = "\\space.fig   ", insertText = " ", filterText = "\\space.fig" },
	{ word = "\\space.punct", label = "\\space.punct   ", insertText = " ", filterText = "\\space.punct" },
	{ word = "\\space.thin", label = "\\space.thin   ", insertText = " ", filterText = "\\space.thin" },
	{ word = "\\space.hair", label = "\\space.hair   ", insertText = " ", filterText = "\\space.hair" },
	{ word = "\\paren.l", label = "\\paren.l  (", insertText = "(", filterText = "\\paren.l" },
	{ word = "\\paren.l.double", label = "\\paren.l.double  ⦅", insertText = "⦅", filterText = "\\paren.l.double" },
	{ word = "\\paren.r", label = "\\paren.r  )", insertText = ")", filterText = "\\paren.r" },
	{ word = "\\paren.r.double", label = "\\paren.r.double  ⦆", insertText = "⦆", filterText = "\\paren.r.double" },
	{ word = "\\paren.t", label = "\\paren.t  ⏜", insertText = "⏜", filterText = "\\paren.t" },
	{ word = "\\paren.b", label = "\\paren.b  ⏝", insertText = "⏝", filterText = "\\paren.b" },
	{ word = "\\brace.l", label = "\\brace.l  {", insertText = "{", filterText = "\\brace.l" },
	{ word = "\\brace.l.double", label = "\\brace.l.double  ⦃", insertText = "⦃", filterText = "\\brace.l.double" },
	{ word = "\\brace.r", label = "\\brace.r  }", insertText = "}", filterText = "\\brace.r" },
	{ word = "\\brace.r.double", label = "\\brace.r.double  ⦄", insertText = "⦄", filterText = "\\brace.r.double" },
	{ word = "\\brace.t", label = "\\brace.t  ⏞", insertText = "⏞", filterText = "\\brace.t" },
	{ word = "\\brace.b", label = "\\brace.b  ⏟", insertText = "⏟", filterText = "\\brace.b" },
	{ word = "\\bracket.l", label = "\\bracket.l  [", insertText = "[", filterText = "\\bracket.l" },
	{
		word = "\\bracket.l.double",
		label = "\\bracket.l.double  ⟦",
		insertText = "⟦",
		filterText = "\\bracket.l.double",
	},
	{ word = "\\bracket.r", label = "\\bracket.r  ]", insertText = "]", filterText = "\\bracket.r" },
	{
		word = "\\bracket.r.double",
		label = "\\bracket.r.double  ⟧",
		insertText = "⟧",
		filterText = "\\bracket.r.double",
	},
	{ word = "\\bracket.t", label = "\\bracket.t  ⎴", insertText = "⎴", filterText = "\\bracket.t" },
	{ word = "\\bracket.b", label = "\\bracket.b  ⎵", insertText = "⎵", filterText = "\\bracket.b" },
	{ word = "\\shell.l", label = "\\shell.l  ❲", insertText = "❲", filterText = "\\shell.l" },
	{ word = "\\shell.l.double", label = "\\shell.l.double  ⟬", insertText = "⟬", filterText = "\\shell.l.double" },
	{ word = "\\shell.r", label = "\\shell.r  ❳", insertText = "❳", filterText = "\\shell.r" },
	{ word = "\\shell.r.double", label = "\\shell.r.double  ⟭", insertText = "⟭", filterText = "\\shell.r.double" },
	{ word = "\\shell.t", label = "\\shell.t  ⏠", insertText = "⏠", filterText = "\\shell.t" },
	{ word = "\\shell.b", label = "\\shell.b  ⏡", insertText = "⏡", filterText = "\\shell.b" },
	{ word = "\\bar.v", label = "\\bar.v  |", insertText = "|", filterText = "\\bar.v" },
	{ word = "\\bar.v.double", label = "\\bar.v.double  ‖", insertText = "‖", filterText = "\\bar.v.double" },
	{ word = "\\bar.v.triple", label = "\\bar.v.triple  ⦀", insertText = "⦀", filterText = "\\bar.v.triple" },
	{ word = "\\bar.v.broken", label = "\\bar.v.broken  ¦", insertText = "¦", filterText = "\\bar.v.broken" },
	{ word = "\\bar.v.circle", label = "\\bar.v.circle  ⦶", insertText = "⦶", filterText = "\\bar.v.circle" },
	{ word = "\\bar.h", label = "\\bar.h  ―", insertText = "―", filterText = "\\bar.h" },
	{ word = "\\fence.l", label = "\\fence.l  ⧘", insertText = "⧘", filterText = "\\fence.l" },
	{ word = "\\fence.l.double", label = "\\fence.l.double  ⧚", insertText = "⧚", filterText = "\\fence.l.double" },
	{ word = "\\fence.r", label = "\\fence.r  ⧙", insertText = "⧙", filterText = "\\fence.r" },
	{ word = "\\fence.r.double", label = "\\fence.r.double  ⧛", insertText = "⧛", filterText = "\\fence.r.double" },
	{ word = "\\fence.dotted", label = "\\fence.dotted  ⦙", insertText = "⦙", filterText = "\\fence.dotted" },
	{ word = "\\angle.", label = "\\angle.  ∠", insertText = "∠", filterText = "\\angle." },
	{ word = "\\angle.l", label = "\\angle.l  ⟨", insertText = "⟨", filterText = "\\angle.l" },
	{ word = "\\angle.l.curly", label = "\\angle.l.curly  ⧼", insertText = "⧼", filterText = "\\angle.l.curly" },
	{ word = "\\angle.l.dot", label = "\\angle.l.dot  ⦑", insertText = "⦑", filterText = "\\angle.l.dot" },
	{ word = "\\angle.l.double", label = "\\angle.l.double  《", insertText = "《", filterText = "\\angle.l.double" },
	{ word = "\\angle.r", label = "\\angle.r  ⟩", insertText = "⟩", filterText = "\\angle.r" },
	{ word = "\\angle.r.curly", label = "\\angle.r.curly  ⧽", insertText = "⧽", filterText = "\\angle.r.curly" },
	{ word = "\\angle.r.dot", label = "\\angle.r.dot  ⦒", insertText = "⦒", filterText = "\\angle.r.dot" },
	{ word = "\\angle.r.double", label = "\\angle.r.double  》", insertText = "》", filterText = "\\angle.r.double" },
	{ word = "\\angle.acute", label = "\\angle.acute  ⦟", insertText = "⦟", filterText = "\\angle.acute" },
	{ word = "\\angle.arc", label = "\\angle.arc  ∡", insertText = "∡", filterText = "\\angle.arc" },
	{ word = "\\angle.arc.rev", label = "\\angle.arc.rev  ⦛", insertText = "⦛", filterText = "\\angle.arc.rev" },
	{ word = "\\angle.oblique", label = "\\angle.oblique  ⦦", insertText = "⦦", filterText = "\\angle.oblique" },
	{ word = "\\angle.rev", label = "\\angle.rev  ⦣", insertText = "⦣", filterText = "\\angle.rev" },
	{ word = "\\angle.right", label = "\\angle.right  ∟", insertText = "∟", filterText = "\\angle.right" },
	{
		word = "\\angle.right.rev",
		label = "\\angle.right.rev  ⯾",
		insertText = "⯾",
		filterText = "\\angle.right.rev",
	},
	{
		word = "\\angle.right.arc",
		label = "\\angle.right.arc  ⊾",
		insertText = "⊾",
		filterText = "\\angle.right.arc",
	},
	{
		word = "\\angle.right.dot",
		label = "\\angle.right.dot  ⦝",
		insertText = "⦝",
		filterText = "\\angle.right.dot",
	},
	{ word = "\\angle.right.sq", label = "\\angle.right.sq  ⦜", insertText = "⦜", filterText = "\\angle.right.sq" },
	{ word = "\\angle.s", label = "\\angle.s  ⦞", insertText = "⦞", filterText = "\\angle.s" },
	{ word = "\\angle.spatial", label = "\\angle.spatial  ⟀", insertText = "⟀", filterText = "\\angle.spatial" },
	{ word = "\\angle.spheric", label = "\\angle.spheric  ∢", insertText = "∢", filterText = "\\angle.spheric" },
	{
		word = "\\angle.spheric.rev",
		label = "\\angle.spheric.rev  ⦠",
		insertText = "⦠",
		filterText = "\\angle.spheric.rev",
	},
	{
		word = "\\angle.spheric.top",
		label = "\\angle.spheric.top  ⦡",
		insertText = "⦡",
		filterText = "\\angle.spheric.top",
	},
	{ word = "\\ceil.l", label = "\\ceil.l  ⌈", insertText = "⌈", filterText = "\\ceil.l" },
	{ word = "\\ceil.r", label = "\\ceil.r  ⌉", insertText = "⌉", filterText = "\\ceil.r" },
	{ word = "\\floor.l", label = "\\floor.l  ⌊", insertText = "⌊", filterText = "\\floor.l" },
	{ word = "\\floor.r", label = "\\floor.r  ⌋", insertText = "⌋", filterText = "\\floor.r" },
	{ word = "\\amp.", label = "\\amp.  &", insertText = "&", filterText = "\\amp." },
	{ word = "\\amp.inv", label = "\\amp.inv  ⅋", insertText = "⅋", filterText = "\\amp.inv" },
	{ word = "\\ast.op", label = "\\ast.op  ∗", insertText = "∗", filterText = "\\ast.op" },
	{ word = "\\ast.basic", label = "\\ast.basic  *", insertText = "*", filterText = "\\ast.basic" },
	{ word = "\\ast.low", label = "\\ast.low  ⁎", insertText = "⁎", filterText = "\\ast.low" },
	{ word = "\\ast.double", label = "\\ast.double  ⁑", insertText = "⁑", filterText = "\\ast.double" },
	{ word = "\\ast.triple", label = "\\ast.triple  ⁂", insertText = "⁂", filterText = "\\ast.triple" },
	{ word = "\\ast.small", label = "\\ast.small  ﹡", insertText = "﹡", filterText = "\\ast.small" },
	{ word = "\\ast.circle", label = "\\ast.circle  ⊛", insertText = "⊛", filterText = "\\ast.circle" },
	{ word = "\\ast.square", label = "\\ast.square  ⧆", insertText = "⧆", filterText = "\\ast.square" },
	{ word = "\\at.", label = "\\at.  @", insertText = "@", filterText = "\\at." },
	{
		word = "\\backslash.circle",
		label = "\\backslash.circle  ⦸",
		insertText = "⦸",
		filterText = "\\backslash.circle",
	},
	{ word = "\\backslash.not", label = "\\backslash.not  ⧷", insertText = "⧷", filterText = "\\backslash.not" },
	{ word = "\\co.", label = "\\co.  ℅", insertText = "℅", filterText = "\\co." },
	{ word = "\\colon.", label = "\\colon.  :", insertText = ":", filterText = "\\colon." },
	{ word = "\\colon.double", label = "\\colon.double  ∷", insertText = "∷", filterText = "\\colon.double" },
	{ word = "\\colon.eq", label = "\\colon.eq  ≔", insertText = "≔", filterText = "\\colon.eq" },
	{
		word = "\\colon.double.eq",
		label = "\\colon.double.eq  ⩴",
		insertText = "⩴",
		filterText = "\\colon.double.eq",
	},
	{ word = "\\comma.", label = "\\comma.  ,", insertText = ",", filterText = "\\comma." },
	{ word = "\\dagger.", label = "\\dagger.  †", insertText = "†", filterText = "\\dagger." },
	{ word = "\\dagger.double", label = "\\dagger.double  ‡", insertText = "‡", filterText = "\\dagger.double" },
	{ word = "\\dash.en", label = "\\dash.en  –", insertText = "–", filterText = "\\dash.en" },
	{ word = "\\dash.em", label = "\\dash.em  —", insertText = "—", filterText = "\\dash.em" },
	{ word = "\\dash.em.two", label = "\\dash.em.two  ⸺", insertText = "⸺", filterText = "\\dash.em.two" },
	{ word = "\\dash.em.three", label = "\\dash.em.three  ⸻", insertText = "⸻", filterText = "\\dash.em.three" },
	{ word = "\\dash.fig", label = "\\dash.fig  ‒", insertText = "‒", filterText = "\\dash.fig" },
	{ word = "\\dash.wave", label = "\\dash.wave  〜", insertText = "〜", filterText = "\\dash.wave" },
	{ word = "\\dash.colon", label = "\\dash.colon  ∹", insertText = "∹", filterText = "\\dash.colon" },
	{ word = "\\dash.circle", label = "\\dash.circle  ⊝", insertText = "⊝", filterText = "\\dash.circle" },
	{
		word = "\\dash.wave.double",
		label = "\\dash.wave.double  〰",
		insertText = "〰",
		filterText = "\\dash.wave.double",
	},
	{ word = "\\dot.op", label = "\\dot.op  ⋅", insertText = "⋅", filterText = "\\dot.op" },
	{ word = "\\dot.basic", label = "\\dot.basic  .", insertText = ".", filterText = "\\dot.basic" },
	{ word = "\\dot.c", label = "\\dot.c  ·", insertText = "·", filterText = "\\dot.c" },
	{ word = "\\dot.circle", label = "\\dot.circle  ⊙", insertText = "⊙", filterText = "\\dot.circle" },
	{ word = "\\dot.circle.big", label = "\\dot.circle.big  ⨀", insertText = "⨀", filterText = "\\dot.circle.big" },
	{ word = "\\dot.square", label = "\\dot.square  ⊡", insertText = "⊡", filterText = "\\dot.square" },
	{ word = "\\dot.double", label = "\\dot.double  ¨", insertText = "¨", filterText = "\\dot.double" },
	{ word = "\\dot.triple", label = "\\dot.triple  ⃛", insertText = "⃛", filterText = "\\dot.triple" },
	{ word = "\\dot.quad", label = "\\dot.quad  ⃜", insertText = "⃜", filterText = "\\dot.quad" },
	{ word = "\\excl.", label = "\\excl.  !", insertText = "!", filterText = "\\excl." },
	{ word = "\\excl.double", label = "\\excl.double  ‼", insertText = "‼", filterText = "\\excl.double" },
	{ word = "\\excl.inv", label = "\\excl.inv  ¡", insertText = "¡", filterText = "\\excl.inv" },
	{ word = "\\excl.quest", label = "\\excl.quest  ⁉", insertText = "⁉", filterText = "\\excl.quest" },
	{ word = "\\quest.", label = "\\quest.  ?", insertText = "?", filterText = "\\quest." },
	{ word = "\\quest.double", label = "\\quest.double  ⁇", insertText = "⁇", filterText = "\\quest.double" },
	{ word = "\\quest.excl", label = "\\quest.excl  ⁈", insertText = "⁈", filterText = "\\quest.excl" },
	{ word = "\\quest.inv", label = "\\quest.inv  ¿", insertText = "¿", filterText = "\\quest.inv" },
	{ word = "\\interrobang.", label = "\\interrobang.  ‽", insertText = "‽", filterText = "\\interrobang." },
	{ word = "\\hash.", label = "\\hash.  #", insertText = "#", filterText = "\\hash." },
	{ word = "\\hyph.", label = "\\hyph.  ‐", insertText = "‐", filterText = "\\hyph." },
	{ word = "\\hyph.minus", label = "\\hyph.minus  -", insertText = "-", filterText = "\\hyph.minus" },
	{ word = "\\hyph.nobreak", label = "\\hyph.nobreak  ‑", insertText = "‑", filterText = "\\hyph.nobreak" },
	{ word = "\\hyph.point", label = "\\hyph.point  ‧", insertText = "‧", filterText = "\\hyph.point" },
	{ word = "\\hyph.soft", label = "\\hyph.soft  ­", insertText = "­", filterText = "\\hyph.soft" },
	{ word = "\\percent.", label = "\\percent.  %", insertText = "%", filterText = "\\percent." },
	{ word = "\\permille.", label = "\\permille.  ‰", insertText = "‰", filterText = "\\permille." },
	{ word = "\\pilcrow.", label = "\\pilcrow.  ¶", insertText = "¶", filterText = "\\pilcrow." },
	{ word = "\\pilcrow.rev", label = "\\pilcrow.rev  ⁋", insertText = "⁋", filterText = "\\pilcrow.rev" },
	{ word = "\\section.", label = "\\section.  §", insertText = "§", filterText = "\\section." },
	{ word = "\\semi.", label = "\\semi.  ;", insertText = ";", filterText = "\\semi." },
	{ word = "\\semi.rev", label = "\\semi.rev  ⁏", insertText = "⁏", filterText = "\\semi.rev" },
	{ word = "\\slash.", label = "\\slash.  /", insertText = "/", filterText = "\\slash." },
	{ word = "\\slash.double", label = "\\slash.double  ⫽", insertText = "⫽", filterText = "\\slash.double" },
	{ word = "\\slash.triple", label = "\\slash.triple  ⫻", insertText = "⫻", filterText = "\\slash.triple" },
	{ word = "\\slash.big", label = "\\slash.big  ⧸", insertText = "⧸", filterText = "\\slash.big" },
	{ word = "\\dots.h.c", label = "\\dots.h.c  ⋯", insertText = "⋯", filterText = "\\dots.h.c" },
	{ word = "\\dots.h", label = "\\dots.h  …", insertText = "…", filterText = "\\dots.h" },
	{ word = "\\dots.v", label = "\\dots.v  ⋮", insertText = "⋮", filterText = "\\dots.v" },
	{ word = "\\dots.down", label = "\\dots.down  ⋱", insertText = "⋱", filterText = "\\dots.down" },
	{ word = "\\dots.up", label = "\\dots.up  ⋰", insertText = "⋰", filterText = "\\dots.up" },
	{ word = "\\tilde.op", label = "\\tilde.op  ∼", insertText = "∼", filterText = "\\tilde.op" },
	{ word = "\\tilde.basic", label = "\\tilde.basic  ~", insertText = "~", filterText = "\\tilde.basic" },
	{ word = "\\tilde.dot", label = "\\tilde.dot  ⩪", insertText = "⩪", filterText = "\\tilde.dot" },
	{ word = "\\tilde.eq", label = "\\tilde.eq  ≃", insertText = "≃", filterText = "\\tilde.eq" },
	{ word = "\\tilde.eq.not", label = "\\tilde.eq.not  ≄", insertText = "≄", filterText = "\\tilde.eq.not" },
	{ word = "\\tilde.eq.rev", label = "\\tilde.eq.rev  ⋍", insertText = "⋍", filterText = "\\tilde.eq.rev" },
	{ word = "\\tilde.equiv", label = "\\tilde.equiv  ≅", insertText = "≅", filterText = "\\tilde.equiv" },
	{
		word = "\\tilde.equiv.not",
		label = "\\tilde.equiv.not  ≇",
		insertText = "≇",
		filterText = "\\tilde.equiv.not",
	},
	{ word = "\\tilde.nequiv", label = "\\tilde.nequiv  ≆", insertText = "≆", filterText = "\\tilde.nequiv" },
	{ word = "\\tilde.not", label = "\\tilde.not  ≁", insertText = "≁", filterText = "\\tilde.not" },
	{ word = "\\tilde.rev", label = "\\tilde.rev  ∽", insertText = "∽", filterText = "\\tilde.rev" },
	{
		word = "\\tilde.rev.equiv",
		label = "\\tilde.rev.equiv  ≌",
		insertText = "≌",
		filterText = "\\tilde.rev.equiv",
	},
	{ word = "\\tilde.triple", label = "\\tilde.triple  ≋", insertText = "≋", filterText = "\\tilde.triple" },
	{ word = "\\acute.", label = "\\acute.  ´", insertText = "´", filterText = "\\acute." },
	{ word = "\\acute.double", label = "\\acute.double  ˝", insertText = "˝", filterText = "\\acute.double" },
	{ word = "\\breve.", label = "\\breve.  ˘", insertText = "˘", filterText = "\\breve." },
	{ word = "\\caret.", label = "\\caret.  ‸", insertText = "‸", filterText = "\\caret." },
	{ word = "\\caron.", label = "\\caron.  ˇ", insertText = "ˇ", filterText = "\\caron." },
	{ word = "\\hat.", label = "\\hat.  ^", insertText = "^", filterText = "\\hat." },
	{ word = "\\diaer.", label = "\\diaer.  ¨", insertText = "¨", filterText = "\\diaer." },
	{ word = "\\grave.", label = "\\grave.  `", insertText = "`", filterText = "\\grave." },
	{ word = "\\macron.", label = "\\macron.  ¯", insertText = "¯", filterText = "\\macron." },
	{ word = "\\quote.l.double", label = "\\quote.l.double  “", insertText = "“", filterText = "\\quote.l.double" },
	{ word = "\\quote.l.single", label = "\\quote.l.single  ‘", insertText = "‘", filterText = "\\quote.l.single" },
	{ word = "\\quote.r.double", label = "\\quote.r.double  ”", insertText = "”", filterText = "\\quote.r.double" },
	{ word = "\\quote.r.single", label = "\\quote.r.single  ’", insertText = "’", filterText = "\\quote.r.single" },
	{
		word = "\\quote.angle.l.double",
		label = "\\quote.angle.l.double  «",
		insertText = "«",
		filterText = "\\quote.angle.l.double",
	},
	{
		word = "\\quote.angle.l.single",
		label = "\\quote.angle.l.single  ‹",
		insertText = "‹",
		filterText = "\\quote.angle.l.single",
	},
	{
		word = "\\quote.angle.r.double",
		label = "\\quote.angle.r.double  »",
		insertText = "»",
		filterText = "\\quote.angle.r.double",
	},
	{
		word = "\\quote.angle.r.single",
		label = "\\quote.angle.r.single  ›",
		insertText = "›",
		filterText = "\\quote.angle.r.single",
	},
	{
		word = "\\quote.high.double",
		label = "\\quote.high.double  ‟",
		insertText = "‟",
		filterText = "\\quote.high.double",
	},
	{
		word = "\\quote.high.single",
		label = "\\quote.high.single  ‛",
		insertText = "‛",
		filterText = "\\quote.high.single",
	},
	{
		word = "\\quote.low.double",
		label = "\\quote.low.double  „",
		insertText = "„",
		filterText = "\\quote.low.double",
	},
	{
		word = "\\quote.low.single",
		label = "\\quote.low.single  ‚",
		insertText = "‚",
		filterText = "\\quote.low.single",
	},
	{ word = "\\prime.", label = "\\prime.  ′", insertText = "′", filterText = "\\prime." },
	{ word = "\\prime.rev", label = "\\prime.rev  ‵", insertText = "‵", filterText = "\\prime.rev" },
	{ word = "\\prime.double", label = "\\prime.double  ″", insertText = "″", filterText = "\\prime.double" },
	{
		word = "\\prime.double.rev",
		label = "\\prime.double.rev  ‶",
		insertText = "‶",
		filterText = "\\prime.double.rev",
	},
	{ word = "\\prime.triple", label = "\\prime.triple  ‴", insertText = "‴", filterText = "\\prime.triple" },
	{
		word = "\\prime.triple.rev",
		label = "\\prime.triple.rev  ‷",
		insertText = "‷",
		filterText = "\\prime.triple.rev",
	},
	{ word = "\\prime.quad", label = "\\prime.quad  ⁗", insertText = "⁗", filterText = "\\prime.quad" },
	{ word = "\\plus.", label = "\\plus.  +", insertText = "+", filterText = "\\plus." },
	{ word = "\\plus.circle", label = "\\plus.circle  ⊕", insertText = "⊕", filterText = "\\plus.circle" },
	{
		word = "\\plus.circle.arrow",
		label = "\\plus.circle.arrow  ⟴",
		insertText = "⟴",
		filterText = "\\plus.circle.arrow",
	},
	{
		word = "\\plus.circle.big",
		label = "\\plus.circle.big  ⨁",
		insertText = "⨁",
		filterText = "\\plus.circle.big",
	},
	{ word = "\\plus.dot", label = "\\plus.dot  ∔", insertText = "∔", filterText = "\\plus.dot" },
	{ word = "\\plus.double", label = "\\plus.double  ⧺", insertText = "⧺", filterText = "\\plus.double" },
	{ word = "\\plus.minus", label = "\\plus.minus  ±", insertText = "±", filterText = "\\plus.minus" },
	{ word = "\\plus.small", label = "\\plus.small  ﹢", insertText = "﹢", filterText = "\\plus.small" },
	{ word = "\\plus.square", label = "\\plus.square  ⊞", insertText = "⊞", filterText = "\\plus.square" },
	{ word = "\\plus.triangle", label = "\\plus.triangle  ⨹", insertText = "⨹", filterText = "\\plus.triangle" },
	{ word = "\\plus.triple", label = "\\plus.triple  ⧻", insertText = "⧻", filterText = "\\plus.triple" },
	{ word = "\\minus.", label = "\\minus.  −", insertText = "−", filterText = "\\minus." },
	{ word = "\\minus.circle", label = "\\minus.circle  ⊖", insertText = "⊖", filterText = "\\minus.circle" },
	{ word = "\\minus.dot", label = "\\minus.dot  ∸", insertText = "∸", filterText = "\\minus.dot" },
	{ word = "\\minus.plus", label = "\\minus.plus  ∓", insertText = "∓", filterText = "\\minus.plus" },
	{ word = "\\minus.square", label = "\\minus.square  ⊟", insertText = "⊟", filterText = "\\minus.square" },
	{ word = "\\minus.tilde", label = "\\minus.tilde  ≂", insertText = "≂", filterText = "\\minus.tilde" },
	{ word = "\\minus.triangle", label = "\\minus.triangle  ⨺", insertText = "⨺", filterText = "\\minus.triangle" },
	{ word = "\\div.", label = "\\div.  ÷", insertText = "÷", filterText = "\\div." },
	{ word = "\\div.circle", label = "\\div.circle  ⨸", insertText = "⨸", filterText = "\\div.circle" },
	{ word = "\\times.", label = "\\times.  ×", insertText = "×", filterText = "\\times." },
	{ word = "\\times.big", label = "\\times.big  ⨉", insertText = "⨉", filterText = "\\times.big" },
	{ word = "\\times.circle", label = "\\times.circle  ⊗", insertText = "⊗", filterText = "\\times.circle" },
	{
		word = "\\times.circle.big",
		label = "\\times.circle.big  ⨂",
		insertText = "⨂",
		filterText = "\\times.circle.big",
	},
	{ word = "\\times.div", label = "\\times.div  ⋇", insertText = "⋇", filterText = "\\times.div" },
	{ word = "\\times.three.l", label = "\\times.three.l  ⋋", insertText = "⋋", filterText = "\\times.three.l" },
	{ word = "\\times.three.r", label = "\\times.three.r  ⋌", insertText = "⋌", filterText = "\\times.three.r" },
	{ word = "\\times.l", label = "\\times.l  ⋉", insertText = "⋉", filterText = "\\times.l" },
	{ word = "\\times.r", label = "\\times.r  ⋊", insertText = "⋊", filterText = "\\times.r" },
	{ word = "\\times.square", label = "\\times.square  ⊠", insertText = "⊠", filterText = "\\times.square" },
	{ word = "\\times.triangle", label = "\\times.triangle  ⨻", insertText = "⨻", filterText = "\\times.triangle" },
	{ word = "\\ratio.", label = "\\ratio.  ∶", insertText = "∶", filterText = "\\ratio." },
	{ word = "\\eq.", label = "\\eq.  =", insertText = "=", filterText = "\\eq." },
	{ word = "\\eq.star", label = "\\eq.star  ≛", insertText = "≛", filterText = "\\eq.star" },
	{ word = "\\eq.circle", label = "\\eq.circle  ⊜", insertText = "⊜", filterText = "\\eq.circle" },
	{ word = "\\eq.colon", label = "\\eq.colon  ≕", insertText = "≕", filterText = "\\eq.colon" },
	{ word = "\\eq.def", label = "\\eq.def  ≝", insertText = "≝", filterText = "\\eq.def" },
	{ word = "\\eq.delta", label = "\\eq.delta  ≜", insertText = "≜", filterText = "\\eq.delta" },
	{ word = "\\eq.equi", label = "\\eq.equi  ≚", insertText = "≚", filterText = "\\eq.equi" },
	{ word = "\\eq.est", label = "\\eq.est  ≙", insertText = "≙", filterText = "\\eq.est" },
	{ word = "\\eq.gt", label = "\\eq.gt  ⋝", insertText = "⋝", filterText = "\\eq.gt" },
	{ word = "\\eq.lt", label = "\\eq.lt  ⋜", insertText = "⋜", filterText = "\\eq.lt" },
	{ word = "\\eq.m", label = "\\eq.m  ≞", insertText = "≞", filterText = "\\eq.m" },
	{ word = "\\eq.not", label = "\\eq.not  ≠", insertText = "≠", filterText = "\\eq.not" },
	{ word = "\\eq.prec", label = "\\eq.prec  ⋞", insertText = "⋞", filterText = "\\eq.prec" },
	{ word = "\\eq.quest", label = "\\eq.quest  ≟", insertText = "≟", filterText = "\\eq.quest" },
	{ word = "\\eq.small", label = "\\eq.small  ﹦", insertText = "﹦", filterText = "\\eq.small" },
	{ word = "\\eq.succ", label = "\\eq.succ  ⋟", insertText = "⋟", filterText = "\\eq.succ" },
	{ word = "\\eq.triple", label = "\\eq.triple  ≡", insertText = "≡", filterText = "\\eq.triple" },
	{ word = "\\eq.quad", label = "\\eq.quad  ≣", insertText = "≣", filterText = "\\eq.quad" },
	{ word = "\\gt.", label = "\\gt.  >", insertText = ">", filterText = "\\gt." },
	{ word = "\\gt.circle", label = "\\gt.circle  ⧁", insertText = "⧁", filterText = "\\gt.circle" },
	{ word = "\\gt.dot", label = "\\gt.dot  ⋗", insertText = "⋗", filterText = "\\gt.dot" },
	{ word = "\\gt.approx", label = "\\gt.approx  ⪆", insertText = "⪆", filterText = "\\gt.approx" },
	{ word = "\\gt.double", label = "\\gt.double  ≫", insertText = "≫", filterText = "\\gt.double" },
	{ word = "\\gt.eq", label = "\\gt.eq  ≥", insertText = "≥", filterText = "\\gt.eq" },
	{ word = "\\gt.eq.slant", label = "\\gt.eq.slant  ⩾", insertText = "⩾", filterText = "\\gt.eq.slant" },
	{ word = "\\gt.eq.lt", label = "\\gt.eq.lt  ⋛", insertText = "⋛", filterText = "\\gt.eq.lt" },
	{ word = "\\gt.eq.not", label = "\\gt.eq.not  ≱", insertText = "≱", filterText = "\\gt.eq.not" },
	{ word = "\\gt.equiv", label = "\\gt.equiv  ≧", insertText = "≧", filterText = "\\gt.equiv" },
	{ word = "\\gt.lt", label = "\\gt.lt  ≷", insertText = "≷", filterText = "\\gt.lt" },
	{ word = "\\gt.lt.not", label = "\\gt.lt.not  ≹", insertText = "≹", filterText = "\\gt.lt.not" },
	{ word = "\\gt.neq", label = "\\gt.neq  ⪈", insertText = "⪈", filterText = "\\gt.neq" },
	{ word = "\\gt.napprox", label = "\\gt.napprox  ⪊", insertText = "⪊", filterText = "\\gt.napprox" },
	{ word = "\\gt.nequiv", label = "\\gt.nequiv  ≩", insertText = "≩", filterText = "\\gt.nequiv" },
	{ word = "\\gt.not", label = "\\gt.not  ≯", insertText = "≯", filterText = "\\gt.not" },
	{ word = "\\gt.ntilde", label = "\\gt.ntilde  ⋧", insertText = "⋧", filterText = "\\gt.ntilde" },
	{ word = "\\gt.small", label = "\\gt.small  ﹥", insertText = "﹥", filterText = "\\gt.small" },
	{ word = "\\gt.tilde", label = "\\gt.tilde  ≳", insertText = "≳", filterText = "\\gt.tilde" },
	{ word = "\\gt.tilde.not", label = "\\gt.tilde.not  ≵", insertText = "≵", filterText = "\\gt.tilde.not" },
	{ word = "\\gt.tri", label = "\\gt.tri  ⊳", insertText = "⊳", filterText = "\\gt.tri" },
	{ word = "\\gt.tri.eq", label = "\\gt.tri.eq  ⊵", insertText = "⊵", filterText = "\\gt.tri.eq" },
	{ word = "\\gt.tri.eq.not", label = "\\gt.tri.eq.not  ⋭", insertText = "⋭", filterText = "\\gt.tri.eq.not" },
	{ word = "\\gt.tri.not", label = "\\gt.tri.not  ⋫", insertText = "⋫", filterText = "\\gt.tri.not" },
	{ word = "\\gt.triple", label = "\\gt.triple  ⋙", insertText = "⋙", filterText = "\\gt.triple" },
	{
		word = "\\gt.triple.nested",
		label = "\\gt.triple.nested  ⫸",
		insertText = "⫸",
		filterText = "\\gt.triple.nested",
	},
	{ word = "\\lt.", label = "\\lt.  <", insertText = "<", filterText = "\\lt." },
	{ word = "\\lt.circle", label = "\\lt.circle  ⧀", insertText = "⧀", filterText = "\\lt.circle" },
	{ word = "\\lt.dot", label = "\\lt.dot  ⋖", insertText = "⋖", filterText = "\\lt.dot" },
	{ word = "\\lt.approx", label = "\\lt.approx  ⪅", insertText = "⪅", filterText = "\\lt.approx" },
	{ word = "\\lt.double", label = "\\lt.double  ≪", insertText = "≪", filterText = "\\lt.double" },
	{ word = "\\lt.eq", label = "\\lt.eq  ≤", insertText = "≤", filterText = "\\lt.eq" },
	{ word = "\\lt.eq.slant", label = "\\lt.eq.slant  ⩽", insertText = "⩽", filterText = "\\lt.eq.slant" },
	{ word = "\\lt.eq.gt", label = "\\lt.eq.gt  ⋚", insertText = "⋚", filterText = "\\lt.eq.gt" },
	{ word = "\\lt.eq.not", label = "\\lt.eq.not  ≰", insertText = "≰", filterText = "\\lt.eq.not" },
	{ word = "\\lt.equiv", label = "\\lt.equiv  ≦", insertText = "≦", filterText = "\\lt.equiv" },
	{ word = "\\lt.gt", label = "\\lt.gt  ≶", insertText = "≶", filterText = "\\lt.gt" },
	{ word = "\\lt.gt.not", label = "\\lt.gt.not  ≸", insertText = "≸", filterText = "\\lt.gt.not" },
	{ word = "\\lt.neq", label = "\\lt.neq  ⪇", insertText = "⪇", filterText = "\\lt.neq" },
	{ word = "\\lt.napprox", label = "\\lt.napprox  ⪉", insertText = "⪉", filterText = "\\lt.napprox" },
	{ word = "\\lt.nequiv", label = "\\lt.nequiv  ≨", insertText = "≨", filterText = "\\lt.nequiv" },
	{ word = "\\lt.not", label = "\\lt.not  ≮", insertText = "≮", filterText = "\\lt.not" },
	{ word = "\\lt.ntilde", label = "\\lt.ntilde  ⋦", insertText = "⋦", filterText = "\\lt.ntilde" },
	{ word = "\\lt.small", label = "\\lt.small  ﹤", insertText = "﹤", filterText = "\\lt.small" },
	{ word = "\\lt.tilde", label = "\\lt.tilde  ≲", insertText = "≲", filterText = "\\lt.tilde" },
	{ word = "\\lt.tilde.not", label = "\\lt.tilde.not  ≴", insertText = "≴", filterText = "\\lt.tilde.not" },
	{ word = "\\lt.tri", label = "\\lt.tri  ⊲", insertText = "⊲", filterText = "\\lt.tri" },
	{ word = "\\lt.tri.eq", label = "\\lt.tri.eq  ⊴", insertText = "⊴", filterText = "\\lt.tri.eq" },
	{ word = "\\lt.tri.eq.not", label = "\\lt.tri.eq.not  ⋬", insertText = "⋬", filterText = "\\lt.tri.eq.not" },
	{ word = "\\lt.tri.not", label = "\\lt.tri.not  ⋪", insertText = "⋪", filterText = "\\lt.tri.not" },
	{ word = "\\lt.triple", label = "\\lt.triple  ⋘", insertText = "⋘", filterText = "\\lt.triple" },
	{
		word = "\\lt.triple.nested",
		label = "\\lt.triple.nested  ⫷",
		insertText = "⫷",
		filterText = "\\lt.triple.nested",
	},
	{ word = "\\approx.", label = "\\approx.  ≈", insertText = "≈", filterText = "\\approx." },
	{ word = "\\approx.eq", label = "\\approx.eq  ≊", insertText = "≊", filterText = "\\approx.eq" },
	{ word = "\\approx.not", label = "\\approx.not  ≉", insertText = "≉", filterText = "\\approx.not" },
	{ word = "\\prec.", label = "\\prec.  ≺", insertText = "≺", filterText = "\\prec." },
	{ word = "\\prec.approx", label = "\\prec.approx  ⪷", insertText = "⪷", filterText = "\\prec.approx" },
	{ word = "\\prec.curly.eq", label = "\\prec.curly.eq  ≼", insertText = "≼", filterText = "\\prec.curly.eq" },
	{
		word = "\\prec.curly.eq.not",
		label = "\\prec.curly.eq.not  ⋠",
		insertText = "⋠",
		filterText = "\\prec.curly.eq.not",
	},
	{ word = "\\prec.double", label = "\\prec.double  ⪻", insertText = "⪻", filterText = "\\prec.double" },
	{ word = "\\prec.eq", label = "\\prec.eq  ⪯", insertText = "⪯", filterText = "\\prec.eq" },
	{ word = "\\prec.equiv", label = "\\prec.equiv  ⪳", insertText = "⪳", filterText = "\\prec.equiv" },
	{ word = "\\prec.napprox", label = "\\prec.napprox  ⪹", insertText = "⪹", filterText = "\\prec.napprox" },
	{ word = "\\prec.neq", label = "\\prec.neq  ⪱", insertText = "⪱", filterText = "\\prec.neq" },
	{ word = "\\prec.nequiv", label = "\\prec.nequiv  ⪵", insertText = "⪵", filterText = "\\prec.nequiv" },
	{ word = "\\prec.not", label = "\\prec.not  ⊀", insertText = "⊀", filterText = "\\prec.not" },
	{ word = "\\prec.ntilde", label = "\\prec.ntilde  ⋨", insertText = "⋨", filterText = "\\prec.ntilde" },
	{ word = "\\prec.tilde", label = "\\prec.tilde  ≾", insertText = "≾", filterText = "\\prec.tilde" },
	{ word = "\\succ.", label = "\\succ.  ≻", insertText = "≻", filterText = "\\succ." },
	{ word = "\\succ.approx", label = "\\succ.approx  ⪸", insertText = "⪸", filterText = "\\succ.approx" },
	{ word = "\\succ.curly.eq", label = "\\succ.curly.eq  ≽", insertText = "≽", filterText = "\\succ.curly.eq" },
	{
		word = "\\succ.curly.eq.not",
		label = "\\succ.curly.eq.not  ⋡",
		insertText = "⋡",
		filterText = "\\succ.curly.eq.not",
	},
	{ word = "\\succ.double", label = "\\succ.double  ⪼", insertText = "⪼", filterText = "\\succ.double" },
	{ word = "\\succ.eq", label = "\\succ.eq  ⪰", insertText = "⪰", filterText = "\\succ.eq" },
	{ word = "\\succ.equiv", label = "\\succ.equiv  ⪴", insertText = "⪴", filterText = "\\succ.equiv" },
	{ word = "\\succ.napprox", label = "\\succ.napprox  ⪺", insertText = "⪺", filterText = "\\succ.napprox" },
	{ word = "\\succ.neq", label = "\\succ.neq  ⪲", insertText = "⪲", filterText = "\\succ.neq" },
	{ word = "\\succ.nequiv", label = "\\succ.nequiv  ⪶", insertText = "⪶", filterText = "\\succ.nequiv" },
	{ word = "\\succ.not", label = "\\succ.not  ⊁", insertText = "⊁", filterText = "\\succ.not" },
	{ word = "\\succ.ntilde", label = "\\succ.ntilde  ⋩", insertText = "⋩", filterText = "\\succ.ntilde" },
	{ word = "\\succ.tilde", label = "\\succ.tilde  ≿", insertText = "≿", filterText = "\\succ.tilde" },
	{ word = "\\equiv.", label = "\\equiv.  ≡", insertText = "≡", filterText = "\\equiv." },
	{ word = "\\equiv.not", label = "\\equiv.not  ≢", insertText = "≢", filterText = "\\equiv.not" },
	{ word = "\\prop.", label = "\\prop.  ∝", insertText = "∝", filterText = "\\prop." },
	{ word = "\\original.", label = "\\original.  ⊶", insertText = "⊶", filterText = "\\original." },
	{ word = "\\image.", label = "\\image.  ⊷", insertText = "⊷", filterText = "\\image." },
	{ word = "\\emptyset.", label = "\\emptyset.  ∅", insertText = "∅", filterText = "\\emptyset." },
	{
		word = "\\emptyset.arrow.r",
		label = "\\emptyset.arrow.r  ⦳",
		insertText = "⦳",
		filterText = "\\emptyset.arrow.r",
	},
	{
		word = "\\emptyset.arrow.l",
		label = "\\emptyset.arrow.l  ⦴",
		insertText = "⦴",
		filterText = "\\emptyset.arrow.l",
	},
	{ word = "\\emptyset.bar", label = "\\emptyset.bar  ⦱", insertText = "⦱", filterText = "\\emptyset.bar" },
	{
		word = "\\emptyset.circle",
		label = "\\emptyset.circle  ⦲",
		insertText = "⦲",
		filterText = "\\emptyset.circle",
	},
	{ word = "\\emptyset.rev", label = "\\emptyset.rev  ⦰", insertText = "⦰", filterText = "\\emptyset.rev" },
	{ word = "\\nothing.", label = "\\nothing.  ∅", insertText = "∅", filterText = "\\nothing." },
	{
		word = "\\nothing.arrow.r",
		label = "\\nothing.arrow.r  ⦳",
		insertText = "⦳",
		filterText = "\\nothing.arrow.r",
	},
	{
		word = "\\nothing.arrow.l",
		label = "\\nothing.arrow.l  ⦴",
		insertText = "⦴",
		filterText = "\\nothing.arrow.l",
	},
	{ word = "\\nothing.bar", label = "\\nothing.bar  ⦱", insertText = "⦱", filterText = "\\nothing.bar" },
	{ word = "\\nothing.circle", label = "\\nothing.circle  ⦲", insertText = "⦲", filterText = "\\nothing.circle" },
	{ word = "\\nothing.rev", label = "\\nothing.rev  ⦰", insertText = "⦰", filterText = "\\nothing.rev" },
	{ word = "\\without.", label = "\\without.  ∖", insertText = "∖", filterText = "\\without." },
	{ word = "\\complement.", label = "\\complement.  ∁", insertText = "∁", filterText = "\\complement." },
	{ word = "\\in.", label = "\\in.  ∈", insertText = "∈", filterText = "\\in." },
	{ word = "\\in.not", label = "\\in.not  ∉", insertText = "∉", filterText = "\\in.not" },
	{ word = "\\in.rev", label = "\\in.rev  ∋", insertText = "∋", filterText = "\\in.rev" },
	{ word = "\\in.rev.not", label = "\\in.rev.not  ∌", insertText = "∌", filterText = "\\in.rev.not" },
	{ word = "\\in.rev.small", label = "\\in.rev.small  ∍", insertText = "∍", filterText = "\\in.rev.small" },
	{ word = "\\in.small", label = "\\in.small  ∊", insertText = "∊", filterText = "\\in.small" },
	{ word = "\\subset.", label = "\\subset.  ⊂", insertText = "⊂", filterText = "\\subset." },
	{ word = "\\subset.dot", label = "\\subset.dot  ⪽", insertText = "⪽", filterText = "\\subset.dot" },
	{ word = "\\subset.double", label = "\\subset.double  ⋐", insertText = "⋐", filterText = "\\subset.double" },
	{ word = "\\subset.eq", label = "\\subset.eq  ⊆", insertText = "⊆", filterText = "\\subset.eq" },
	{ word = "\\subset.eq.not", label = "\\subset.eq.not  ⊈", insertText = "⊈", filterText = "\\subset.eq.not" },
	{ word = "\\subset.eq.sq", label = "\\subset.eq.sq  ⊑", insertText = "⊑", filterText = "\\subset.eq.sq" },
	{
		word = "\\subset.eq.sq.not",
		label = "\\subset.eq.sq.not  ⋢",
		insertText = "⋢",
		filterText = "\\subset.eq.sq.not",
	},
	{ word = "\\subset.neq", label = "\\subset.neq  ⊊", insertText = "⊊", filterText = "\\subset.neq" },
	{ word = "\\subset.not", label = "\\subset.not  ⊄", insertText = "⊄", filterText = "\\subset.not" },
	{ word = "\\subset.sq", label = "\\subset.sq  ⊏", insertText = "⊏", filterText = "\\subset.sq" },
	{ word = "\\subset.sq.neq", label = "\\subset.sq.neq  ⋤", insertText = "⋤", filterText = "\\subset.sq.neq" },
	{ word = "\\supset.", label = "\\supset.  ⊃", insertText = "⊃", filterText = "\\supset." },
	{ word = "\\supset.dot", label = "\\supset.dot  ⪾", insertText = "⪾", filterText = "\\supset.dot" },
	{ word = "\\supset.double", label = "\\supset.double  ⋑", insertText = "⋑", filterText = "\\supset.double" },
	{ word = "\\supset.eq", label = "\\supset.eq  ⊇", insertText = "⊇", filterText = "\\supset.eq" },
	{ word = "\\supset.eq.not", label = "\\supset.eq.not  ⊉", insertText = "⊉", filterText = "\\supset.eq.not" },
	{ word = "\\supset.eq.sq", label = "\\supset.eq.sq  ⊒", insertText = "⊒", filterText = "\\supset.eq.sq" },
	{
		word = "\\supset.eq.sq.not",
		label = "\\supset.eq.sq.not  ⋣",
		insertText = "⋣",
		filterText = "\\supset.eq.sq.not",
	},
	{ word = "\\supset.neq", label = "\\supset.neq  ⊋", insertText = "⊋", filterText = "\\supset.neq" },
	{ word = "\\supset.not", label = "\\supset.not  ⊅", insertText = "⊅", filterText = "\\supset.not" },
	{ word = "\\supset.sq", label = "\\supset.sq  ⊐", insertText = "⊐", filterText = "\\supset.sq" },
	{ word = "\\supset.sq.neq", label = "\\supset.sq.neq  ⋥", insertText = "⋥", filterText = "\\supset.sq.neq" },
	{ word = "\\union.", label = "\\union.  ∪", insertText = "∪", filterText = "\\union." },
	{ word = "\\union.arrow", label = "\\union.arrow  ⊌", insertText = "⊌", filterText = "\\union.arrow" },
	{ word = "\\union.big", label = "\\union.big  ⋃", insertText = "⋃", filterText = "\\union.big" },
	{ word = "\\union.dot", label = "\\union.dot  ⊍", insertText = "⊍", filterText = "\\union.dot" },
	{ word = "\\union.dot.big", label = "\\union.dot.big  ⨃", insertText = "⨃", filterText = "\\union.dot.big" },
	{ word = "\\union.double", label = "\\union.double  ⋓", insertText = "⋓", filterText = "\\union.double" },
	{ word = "\\union.minus", label = "\\union.minus  ⩁", insertText = "⩁", filterText = "\\union.minus" },
	{ word = "\\union.or", label = "\\union.or  ⩅", insertText = "⩅", filterText = "\\union.or" },
	{ word = "\\union.plus", label = "\\union.plus  ⊎", insertText = "⊎", filterText = "\\union.plus" },
	{ word = "\\union.plus.big", label = "\\union.plus.big  ⨄", insertText = "⨄", filterText = "\\union.plus.big" },
	{ word = "\\union.sq", label = "\\union.sq  ⊔", insertText = "⊔", filterText = "\\union.sq" },
	{ word = "\\union.sq.big", label = "\\union.sq.big  ⨆", insertText = "⨆", filterText = "\\union.sq.big" },
	{
		word = "\\union.sq.double",
		label = "\\union.sq.double  ⩏",
		insertText = "⩏",
		filterText = "\\union.sq.double",
	},
	{ word = "\\sect.", label = "\\sect.  ∩", insertText = "∩", filterText = "\\sect." },
	{ word = "\\sect.and", label = "\\sect.and  ⩄", insertText = "⩄", filterText = "\\sect.and" },
	{ word = "\\sect.big", label = "\\sect.big  ⋂", insertText = "⋂", filterText = "\\sect.big" },
	{ word = "\\sect.dot", label = "\\sect.dot  ⩀", insertText = "⩀", filterText = "\\sect.dot" },
	{ word = "\\sect.double", label = "\\sect.double  ⋒", insertText = "⋒", filterText = "\\sect.double" },
	{ word = "\\sect.sq", label = "\\sect.sq  ⊓", insertText = "⊓", filterText = "\\sect.sq" },
	{ word = "\\sect.sq.big", label = "\\sect.sq.big  ⨅", insertText = "⨅", filterText = "\\sect.sq.big" },
	{ word = "\\sect.sq.double", label = "\\sect.sq.double  ⩎", insertText = "⩎", filterText = "\\sect.sq.double" },
	{ word = "\\infinity.", label = "\\infinity.  ∞", insertText = "∞", filterText = "\\infinity." },
	{ word = "\\infinity.bar", label = "\\infinity.bar  ⧞", insertText = "⧞", filterText = "\\infinity.bar" },
	{
		word = "\\infinity.incomplete",
		label = "\\infinity.incomplete  ⧜",
		insertText = "⧜",
		filterText = "\\infinity.incomplete",
	},
	{ word = "\\infinity.tie", label = "\\infinity.tie  ⧝", insertText = "⧝", filterText = "\\infinity.tie" },
	{ word = "\\oo.", label = "\\oo.  ∞", insertText = "∞", filterText = "\\oo." },
	{ word = "\\diff.", label = "\\diff.  ∂", insertText = "∂", filterText = "\\diff." },
	{ word = "\\partial.", label = "\\partial.  ∂", insertText = "∂", filterText = "\\partial." },
	{ word = "\\gradient.", label = "\\gradient.  ∇", insertText = "∇", filterText = "\\gradient." },
	{ word = "\\nabla.", label = "\\nabla.  ∇", insertText = "∇", filterText = "\\nabla." },
	{ word = "\\sum.", label = "\\sum.  ∑", insertText = "∑", filterText = "\\sum." },
	{ word = "\\sum.integral", label = "\\sum.integral  ⨋", insertText = "⨋", filterText = "\\sum.integral" },
	{ word = "\\product.", label = "\\product.  ∏", insertText = "∏", filterText = "\\product." },
	{ word = "\\product.co", label = "\\product.co  ∐", insertText = "∐", filterText = "\\product.co" },
	{ word = "\\integral.", label = "\\integral.  ∫", insertText = "∫", filterText = "\\integral." },
	{
		word = "\\integral.arrow.hook",
		label = "\\integral.arrow.hook  ⨗",
		insertText = "⨗",
		filterText = "\\integral.arrow.hook",
	},
	{ word = "\\integral.ccw", label = "\\integral.ccw  ⨑", insertText = "⨑", filterText = "\\integral.ccw" },
	{ word = "\\integral.cont", label = "\\integral.cont  ∮", insertText = "∮", filterText = "\\integral.cont" },
	{
		word = "\\integral.cont.ccw",
		label = "\\integral.cont.ccw  ∳",
		insertText = "∳",
		filterText = "\\integral.cont.ccw",
	},
	{
		word = "\\integral.cont.cw",
		label = "\\integral.cont.cw  ∲",
		insertText = "∲",
		filterText = "\\integral.cont.cw",
	},
	{ word = "\\integral.cw", label = "\\integral.cw  ∱", insertText = "∱", filterText = "\\integral.cw" },
	{ word = "\\integral.dash", label = "\\integral.dash  ⨍", insertText = "⨍", filterText = "\\integral.dash" },
	{
		word = "\\integral.dash.double",
		label = "\\integral.dash.double  ⨎",
		insertText = "⨎",
		filterText = "\\integral.dash.double",
	},
	{
		word = "\\integral.double",
		label = "\\integral.double  ∬",
		insertText = "∬",
		filterText = "\\integral.double",
	},
	{ word = "\\integral.quad", label = "\\integral.quad  ⨌", insertText = "⨌", filterText = "\\integral.quad" },
	{ word = "\\integral.sect", label = "\\integral.sect  ⨙", insertText = "⨙", filterText = "\\integral.sect" },
	{ word = "\\integral.slash", label = "\\integral.slash  ⨏", insertText = "⨏", filterText = "\\integral.slash" },
	{
		word = "\\integral.square",
		label = "\\integral.square  ⨖",
		insertText = "⨖",
		filterText = "\\integral.square",
	},
	{ word = "\\integral.surf", label = "\\integral.surf  ∯", insertText = "∯", filterText = "\\integral.surf" },
	{ word = "\\integral.times", label = "\\integral.times  ⨘", insertText = "⨘", filterText = "\\integral.times" },
	{
		word = "\\integral.triple",
		label = "\\integral.triple  ∭",
		insertText = "∭",
		filterText = "\\integral.triple",
	},
	{ word = "\\integral.union", label = "\\integral.union  ⨚", insertText = "⨚", filterText = "\\integral.union" },
	{ word = "\\integral.vol", label = "\\integral.vol  ∰", insertText = "∰", filterText = "\\integral.vol" },
	{ word = "\\laplace.", label = "\\laplace.  ∆", insertText = "∆", filterText = "\\laplace." },
	{ word = "\\forall.", label = "\\forall.  ∀", insertText = "∀", filterText = "\\forall." },
	{ word = "\\exists.", label = "\\exists.  ∃", insertText = "∃", filterText = "\\exists." },
	{ word = "\\exists.not", label = "\\exists.not  ∄", insertText = "∄", filterText = "\\exists.not" },
	{ word = "\\top.", label = "\\top.  ⊤", insertText = "⊤", filterText = "\\top." },
	{ word = "\\bot.", label = "\\bot.  ⊥", insertText = "⊥", filterText = "\\bot." },
	{ word = "\\not.", label = "\\not.  ¬", insertText = "¬", filterText = "\\not." },
	{ word = "\\and.", label = "\\and.  ∧", insertText = "∧", filterText = "\\and." },
	{ word = "\\and.big", label = "\\and.big  ⋀", insertText = "⋀", filterText = "\\and.big" },
	{ word = "\\and.curly", label = "\\and.curly  ⋏", insertText = "⋏", filterText = "\\and.curly" },
	{ word = "\\and.dot", label = "\\and.dot  ⟑", insertText = "⟑", filterText = "\\and.dot" },
	{ word = "\\and.double", label = "\\and.double  ⩓", insertText = "⩓", filterText = "\\and.double" },
	{ word = "\\or.", label = "\\or.  ∨", insertText = "∨", filterText = "\\or." },
	{ word = "\\or.big", label = "\\or.big  ⋁", insertText = "⋁", filterText = "\\or.big" },
	{ word = "\\or.curly", label = "\\or.curly  ⋎", insertText = "⋎", filterText = "\\or.curly" },
	{ word = "\\or.dot", label = "\\or.dot  ⟇", insertText = "⟇", filterText = "\\or.dot" },
	{ word = "\\or.double", label = "\\or.double  ⩔", insertText = "⩔", filterText = "\\or.double" },
	{ word = "\\xor.", label = "\\xor.  ⊕", insertText = "⊕", filterText = "\\xor." },
	{ word = "\\xor.big", label = "\\xor.big  ⨁", insertText = "⨁", filterText = "\\xor.big" },
	{ word = "\\models.", label = "\\models.  ⊧", insertText = "⊧", filterText = "\\models." },
	{ word = "\\forces.", label = "\\forces.  ⊩", insertText = "⊩", filterText = "\\forces." },
	{ word = "\\forces.not", label = "\\forces.not  ⊮", insertText = "⊮", filterText = "\\forces.not" },
	{ word = "\\therefore.", label = "\\therefore.  ∴", insertText = "∴", filterText = "\\therefore." },
	{ word = "\\because.", label = "\\because.  ∵", insertText = "∵", filterText = "\\because." },
	{ word = "\\qed.", label = "\\qed.  ∎", insertText = "∎", filterText = "\\qed." },
	{ word = "\\compose.", label = "\\compose.  ∘", insertText = "∘", filterText = "\\compose." },
	{ word = "\\convolve.", label = "\\convolve.  ∗", insertText = "∗", filterText = "\\convolve." },
	{ word = "\\multimap.", label = "\\multimap.  ⊸", insertText = "⊸", filterText = "\\multimap." },
	{
		word = "\\multimap.double",
		label = "\\multimap.double  ⧟",
		insertText = "⧟",
		filterText = "\\multimap.double",
	},
	{ word = "\\tiny.", label = "\\tiny.  ⧾", insertText = "⧾", filterText = "\\tiny." },
	{ word = "\\miny.", label = "\\miny.  ⧿", insertText = "⧿", filterText = "\\miny." },
	{ word = "\\divides.", label = "\\divides.  ∣", insertText = "∣", filterText = "\\divides." },
	{ word = "\\divides.not", label = "\\divides.not  ∤", insertText = "∤", filterText = "\\divides.not" },
	{ word = "\\wreath.", label = "\\wreath.  ≀", insertText = "≀", filterText = "\\wreath." },
	{ word = "\\parallel.", label = "\\parallel.  ∥", insertText = "∥", filterText = "\\parallel." },
	{
		word = "\\parallel.struck",
		label = "\\parallel.struck  ⫲",
		insertText = "⫲",
		filterText = "\\parallel.struck",
	},
	{
		word = "\\parallel.circle",
		label = "\\parallel.circle  ⦷",
		insertText = "⦷",
		filterText = "\\parallel.circle",
	},
	{ word = "\\parallel.eq", label = "\\parallel.eq  ⋕", insertText = "⋕", filterText = "\\parallel.eq" },
	{ word = "\\parallel.equiv", label = "\\parallel.equiv  ⩨", insertText = "⩨", filterText = "\\parallel.equiv" },
	{ word = "\\parallel.not", label = "\\parallel.not  ∦", insertText = "∦", filterText = "\\parallel.not" },
	{
		word = "\\parallel.slanted.eq",
		label = "\\parallel.slanted.eq  ⧣",
		insertText = "⧣",
		filterText = "\\parallel.slanted.eq",
	},
	{
		word = "\\parallel.slanted.eq.tilde",
		label = "\\parallel.slanted.eq.tilde  ⧤",
		insertText = "⧤",
		filterText = "\\parallel.slanted.eq.tilde",
	},
	{
		word = "\\parallel.slanted.equiv",
		label = "\\parallel.slanted.equiv  ⧥",
		insertText = "⧥",
		filterText = "\\parallel.slanted.equiv",
	},
	{ word = "\\parallel.tilde", label = "\\parallel.tilde  ⫳", insertText = "⫳", filterText = "\\parallel.tilde" },
	{ word = "\\perp.", label = "\\perp.  ⟂", insertText = "⟂", filterText = "\\perp." },
	{ word = "\\perp.circle", label = "\\perp.circle  ⦹", insertText = "⦹", filterText = "\\perp.circle" },
	{ word = "\\diameter.", label = "\\diameter.  ⌀", insertText = "⌀", filterText = "\\diameter." },
	{ word = "\\join.", label = "\\join.  ⨝", insertText = "⨝", filterText = "\\join." },
	{ word = "\\join.r", label = "\\join.r  ⟖", insertText = "⟖", filterText = "\\join.r" },
	{ word = "\\join.l", label = "\\join.l  ⟕", insertText = "⟕", filterText = "\\join.l" },
	{ word = "\\join.l.r", label = "\\join.l.r  ⟗", insertText = "⟗", filterText = "\\join.l.r" },
	{ word = "\\degree.", label = "\\degree.  °", insertText = "°", filterText = "\\degree." },
	{ word = "\\degree.c", label = "\\degree.c  ℃", insertText = "℃", filterText = "\\degree.c" },
	{ word = "\\degree.f", label = "\\degree.f  ℉", insertText = "℉", filterText = "\\degree.f" },
	{ word = "\\smash.", label = "\\smash.  ⨳", insertText = "⨳", filterText = "\\smash." },
	{ word = "\\bitcoin.", label = "\\bitcoin.  ₿", insertText = "₿", filterText = "\\bitcoin." },
	{ word = "\\dollar.", label = "\\dollar.  $", insertText = "$", filterText = "\\dollar." },
	{ word = "\\euro.", label = "\\euro.  €", insertText = "€", filterText = "\\euro." },
	{ word = "\\franc.", label = "\\franc.  ₣", insertText = "₣", filterText = "\\franc." },
	{ word = "\\lira.", label = "\\lira.  ₺", insertText = "₺", filterText = "\\lira." },
	{ word = "\\peso.", label = "\\peso.  ₱", insertText = "₱", filterText = "\\peso." },
	{ word = "\\pound.", label = "\\pound.  £", insertText = "£", filterText = "\\pound." },
	{ word = "\\ruble.", label = "\\ruble.  ₽", insertText = "₽", filterText = "\\ruble." },
	{ word = "\\rupee.", label = "\\rupee.  ₹", insertText = "₹", filterText = "\\rupee." },
	{ word = "\\won.", label = "\\won.  ₩", insertText = "₩", filterText = "\\won." },
	{ word = "\\yen.", label = "\\yen.  ¥", insertText = "¥", filterText = "\\yen." },
	{ word = "\\ballot.", label = "\\ballot.  ☐", insertText = "☐", filterText = "\\ballot." },
	{ word = "\\ballot.cross", label = "\\ballot.cross  ☒", insertText = "☒", filterText = "\\ballot.cross" },
	{ word = "\\ballot.check", label = "\\ballot.check  ☑", insertText = "☑", filterText = "\\ballot.check" },
	{
		word = "\\ballot.check.heavy",
		label = "\\ballot.check.heavy  🗹",
		insertText = "🗹",
		filterText = "\\ballot.check.heavy",
	},
	{ word = "\\checkmark.", label = "\\checkmark.  ✓", insertText = "✓", filterText = "\\checkmark." },
	{
		word = "\\checkmark.light",
		label = "\\checkmark.light  🗸",
		insertText = "🗸",
		filterText = "\\checkmark.light",
	},
	{
		word = "\\checkmark.heavy",
		label = "\\checkmark.heavy  ✔",
		insertText = "✔",
		filterText = "\\checkmark.heavy",
	},
	{ word = "\\crossmark.", label = "\\crossmark.  ✗", insertText = "✗", filterText = "\\crossmark." },
	{
		word = "\\crossmark.heavy",
		label = "\\crossmark.heavy  ✘",
		insertText = "✘",
		filterText = "\\crossmark.heavy",
	},
	{ word = "\\floral.", label = "\\floral.  ❦", insertText = "❦", filterText = "\\floral." },
	{ word = "\\floral.l", label = "\\floral.l  ☙", insertText = "☙", filterText = "\\floral.l" },
	{ word = "\\floral.r", label = "\\floral.r  ❧", insertText = "❧", filterText = "\\floral.r" },
	{ word = "\\refmark.", label = "\\refmark.  ※", insertText = "※", filterText = "\\refmark." },
	{ word = "\\copyright.", label = "\\copyright.  ©", insertText = "©", filterText = "\\copyright." },
	{
		word = "\\copyright.sound",
		label = "\\copyright.sound  ℗",
		insertText = "℗",
		filterText = "\\copyright.sound",
	},
	{ word = "\\copyleft.", label = "\\copyleft.  🄯", insertText = "🄯", filterText = "\\copyleft." },
	{ word = "\\trademark.", label = "\\trademark.  ™", insertText = "™", filterText = "\\trademark." },
	{
		word = "\\trademark.registered",
		label = "\\trademark.registered  ®",
		insertText = "®",
		filterText = "\\trademark.registered",
	},
	{
		word = "\\trademark.service",
		label = "\\trademark.service  ℠",
		insertText = "℠",
		filterText = "\\trademark.service",
	},
	{ word = "\\maltese.", label = "\\maltese.  ✠", insertText = "✠", filterText = "\\maltese." },
	{
		word = "\\suit.club.filled",
		label = "\\suit.club.filled  ♣",
		insertText = "♣",
		filterText = "\\suit.club.filled",
	},
	{
		word = "\\suit.club.stroked",
		label = "\\suit.club.stroked  ♧",
		insertText = "♧",
		filterText = "\\suit.club.stroked",
	},
	{
		word = "\\suit.diamond.filled",
		label = "\\suit.diamond.filled  ♦",
		insertText = "♦",
		filterText = "\\suit.diamond.filled",
	},
	{
		word = "\\suit.diamond.stroked",
		label = "\\suit.diamond.stroked  ♢",
		insertText = "♢",
		filterText = "\\suit.diamond.stroked",
	},
	{
		word = "\\suit.heart.filled",
		label = "\\suit.heart.filled  ♥",
		insertText = "♥",
		filterText = "\\suit.heart.filled",
	},
	{
		word = "\\suit.heart.stroked",
		label = "\\suit.heart.stroked  ♡",
		insertText = "♡",
		filterText = "\\suit.heart.stroked",
	},
	{
		word = "\\suit.spade.filled",
		label = "\\suit.spade.filled  ♠",
		insertText = "♠",
		filterText = "\\suit.spade.filled",
	},
	{
		word = "\\suit.spade.stroked",
		label = "\\suit.spade.stroked  ♤",
		insertText = "♤",
		filterText = "\\suit.spade.stroked",
	},
	{ word = "\\note.up", label = "\\note.up  🎜", insertText = "🎜", filterText = "\\note.up" },
	{ word = "\\note.down", label = "\\note.down  🎝", insertText = "🎝", filterText = "\\note.down" },
	{ word = "\\note.whole", label = "\\note.whole  𝅝", insertText = "𝅝", filterText = "\\note.whole" },
	{ word = "\\note.half", label = "\\note.half  𝅗𝅥", insertText = "𝅗𝅥", filterText = "\\note.half" },
	{ word = "\\note.quarter", label = "\\note.quarter  𝅘𝅥", insertText = "𝅘𝅥", filterText = "\\note.quarter" },
	{
		word = "\\note.quarter.alt",
		label = "\\note.quarter.alt  ♩",
		insertText = "♩",
		filterText = "\\note.quarter.alt",
	},
	{ word = "\\note.eighth", label = "\\note.eighth  𝅘𝅥𝅮", insertText = "𝅘𝅥𝅮", filterText = "\\note.eighth" },
	{
		word = "\\note.eighth.alt",
		label = "\\note.eighth.alt  ♪",
		insertText = "♪",
		filterText = "\\note.eighth.alt",
	},
	{
		word = "\\note.eighth.beamed",
		label = "\\note.eighth.beamed  ♫",
		insertText = "♫",
		filterText = "\\note.eighth.beamed",
	},
	{
		word = "\\note.sixteenth",
		label = "\\note.sixteenth  𝅘𝅥𝅯",
		insertText = "𝅘𝅥𝅯",
		filterText = "\\note.sixteenth",
	},
	{
		word = "\\note.sixteenth.beamed",
		label = "\\note.sixteenth.beamed  ♬",
		insertText = "♬",
		filterText = "\\note.sixteenth.beamed",
	},
	{ word = "\\note.grace", label = "\\note.grace  𝆕", insertText = "𝆕", filterText = "\\note.grace" },
	{
		word = "\\note.grace.slash",
		label = "\\note.grace.slash  𝆔",
		insertText = "𝆔",
		filterText = "\\note.grace.slash",
	},
	{ word = "\\rest.whole", label = "\\rest.whole  𝄻", insertText = "𝄻", filterText = "\\rest.whole" },
	{ word = "\\rest.multiple", label = "\\rest.multiple  𝄺", insertText = "𝄺", filterText = "\\rest.multiple" },
	{
		word = "\\rest.multiple.measure",
		label = "\\rest.multiple.measure  𝄩",
		insertText = "𝄩",
		filterText = "\\rest.multiple.measure",
	},
	{ word = "\\rest.half", label = "\\rest.half  𝄼", insertText = "𝄼", filterText = "\\rest.half" },
	{ word = "\\rest.quarter", label = "\\rest.quarter  𝄽", insertText = "𝄽", filterText = "\\rest.quarter" },
	{ word = "\\rest.eighth", label = "\\rest.eighth  𝄾", insertText = "𝄾", filterText = "\\rest.eighth" },
	{
		word = "\\rest.sixteenth",
		label = "\\rest.sixteenth  𝄿",
		insertText = "𝄿",
		filterText = "\\rest.sixteenth",
	},
	{ word = "\\natural.", label = "\\natural.  ♮", insertText = "♮", filterText = "\\natural." },
	{ word = "\\natural.t", label = "\\natural.t  𝄮", insertText = "𝄮", filterText = "\\natural.t" },
	{ word = "\\natural.b", label = "\\natural.b  𝄯", insertText = "𝄯", filterText = "\\natural.b" },
	{ word = "\\flat.", label = "\\flat.  ♭", insertText = "♭", filterText = "\\flat." },
	{ word = "\\flat.t", label = "\\flat.t  𝄬", insertText = "𝄬", filterText = "\\flat.t" },
	{ word = "\\flat.b", label = "\\flat.b  𝄭", insertText = "𝄭", filterText = "\\flat.b" },
	{ word = "\\flat.double", label = "\\flat.double  𝄫", insertText = "𝄫", filterText = "\\flat.double" },
	{ word = "\\flat.quarter", label = "\\flat.quarter  𝄳", insertText = "𝄳", filterText = "\\flat.quarter" },
	{ word = "\\sharp.", label = "\\sharp.  ♯", insertText = "♯", filterText = "\\sharp." },
	{ word = "\\sharp.t", label = "\\sharp.t  𝄰", insertText = "𝄰", filterText = "\\sharp.t" },
	{ word = "\\sharp.b", label = "\\sharp.b  𝄱", insertText = "𝄱", filterText = "\\sharp.b" },
	{ word = "\\sharp.double", label = "\\sharp.double  𝄪", insertText = "𝄪", filterText = "\\sharp.double" },
	{ word = "\\sharp.quarter", label = "\\sharp.quarter  𝄲", insertText = "𝄲", filterText = "\\sharp.quarter" },
	{ word = "\\bullet.", label = "\\bullet.  •", insertText = "•", filterText = "\\bullet." },
	{ word = "\\circle.stroked", label = "\\circle.stroked  ○", insertText = "○", filterText = "\\circle.stroked" },
	{
		word = "\\circle.stroked.tiny",
		label = "\\circle.stroked.tiny  ∘",
		insertText = "∘",
		filterText = "\\circle.stroked.tiny",
	},
	{
		word = "\\circle.stroked.small",
		label = "\\circle.stroked.small  ⚬",
		insertText = "⚬",
		filterText = "\\circle.stroked.small",
	},
	{
		word = "\\circle.stroked.big",
		label = "\\circle.stroked.big  ◯",
		insertText = "◯",
		filterText = "\\circle.stroked.big",
	},
	{ word = "\\circle.filled", label = "\\circle.filled  ●", insertText = "●", filterText = "\\circle.filled" },
	{
		word = "\\circle.filled.tiny",
		label = "\\circle.filled.tiny  ⦁",
		insertText = "⦁",
		filterText = "\\circle.filled.tiny",
	},
	{
		word = "\\circle.filled.small",
		label = "\\circle.filled.small  ∙",
		insertText = "∙",
		filterText = "\\circle.filled.small",
	},
	{
		word = "\\circle.filled.big",
		label = "\\circle.filled.big  ⬤",
		insertText = "⬤",
		filterText = "\\circle.filled.big",
	},
	{ word = "\\circle.dotted", label = "\\circle.dotted  ◌", insertText = "◌", filterText = "\\circle.dotted" },
	{ word = "\\circle.nested", label = "\\circle.nested  ⊚", insertText = "⊚", filterText = "\\circle.nested" },
	{
		word = "\\ellipse.stroked.h",
		label = "\\ellipse.stroked.h  ⬭",
		insertText = "⬭",
		filterText = "\\ellipse.stroked.h",
	},
	{
		word = "\\ellipse.stroked.v",
		label = "\\ellipse.stroked.v  ⬯",
		insertText = "⬯",
		filterText = "\\ellipse.stroked.v",
	},
	{
		word = "\\ellipse.filled.h",
		label = "\\ellipse.filled.h  ⬬",
		insertText = "⬬",
		filterText = "\\ellipse.filled.h",
	},
	{
		word = "\\ellipse.filled.v",
		label = "\\ellipse.filled.v  ⬮",
		insertText = "⬮",
		filterText = "\\ellipse.filled.v",
	},
	{
		word = "\\triangle.stroked.t",
		label = "\\triangle.stroked.t  △",
		insertText = "△",
		filterText = "\\triangle.stroked.t",
	},
	{
		word = "\\triangle.stroked.b",
		label = "\\triangle.stroked.b  ▽",
		insertText = "▽",
		filterText = "\\triangle.stroked.b",
	},
	{
		word = "\\triangle.stroked.r",
		label = "\\triangle.stroked.r  ▷",
		insertText = "▷",
		filterText = "\\triangle.stroked.r",
	},
	{
		word = "\\triangle.stroked.l",
		label = "\\triangle.stroked.l  ◁",
		insertText = "◁",
		filterText = "\\triangle.stroked.l",
	},
	{
		word = "\\triangle.stroked.bl",
		label = "\\triangle.stroked.bl  ◺",
		insertText = "◺",
		filterText = "\\triangle.stroked.bl",
	},
	{
		word = "\\triangle.stroked.br",
		label = "\\triangle.stroked.br  ◿",
		insertText = "◿",
		filterText = "\\triangle.stroked.br",
	},
	{
		word = "\\triangle.stroked.tl",
		label = "\\triangle.stroked.tl  ◸",
		insertText = "◸",
		filterText = "\\triangle.stroked.tl",
	},
	{
		word = "\\triangle.stroked.tr",
		label = "\\triangle.stroked.tr  ◹",
		insertText = "◹",
		filterText = "\\triangle.stroked.tr",
	},
	{
		word = "\\triangle.stroked.small.t",
		label = "\\triangle.stroked.small.t  ▵",
		insertText = "▵",
		filterText = "\\triangle.stroked.small.t",
	},
	{
		word = "\\triangle.stroked.small.b",
		label = "\\triangle.stroked.small.b  ▿",
		insertText = "▿",
		filterText = "\\triangle.stroked.small.b",
	},
	{
		word = "\\triangle.stroked.small.r",
		label = "\\triangle.stroked.small.r  ▹",
		insertText = "▹",
		filterText = "\\triangle.stroked.small.r",
	},
	{
		word = "\\triangle.stroked.small.l",
		label = "\\triangle.stroked.small.l  ◃",
		insertText = "◃",
		filterText = "\\triangle.stroked.small.l",
	},
	{
		word = "\\triangle.stroked.rounded",
		label = "\\triangle.stroked.rounded  🛆",
		insertText = "🛆",
		filterText = "\\triangle.stroked.rounded",
	},
	{
		word = "\\triangle.stroked.nested",
		label = "\\triangle.stroked.nested  ⟁",
		insertText = "⟁",
		filterText = "\\triangle.stroked.nested",
	},
	{
		word = "\\triangle.stroked.dot",
		label = "\\triangle.stroked.dot  ◬",
		insertText = "◬",
		filterText = "\\triangle.stroked.dot",
	},
	{
		word = "\\triangle.filled.t",
		label = "\\triangle.filled.t  ▲",
		insertText = "▲",
		filterText = "\\triangle.filled.t",
	},
	{
		word = "\\triangle.filled.b",
		label = "\\triangle.filled.b  ▼",
		insertText = "▼",
		filterText = "\\triangle.filled.b",
	},
	{
		word = "\\triangle.filled.r",
		label = "\\triangle.filled.r  ▶",
		insertText = "▶",
		filterText = "\\triangle.filled.r",
	},
	{
		word = "\\triangle.filled.l",
		label = "\\triangle.filled.l  ◀",
		insertText = "◀",
		filterText = "\\triangle.filled.l",
	},
	{
		word = "\\triangle.filled.bl",
		label = "\\triangle.filled.bl  ◣",
		insertText = "◣",
		filterText = "\\triangle.filled.bl",
	},
	{
		word = "\\triangle.filled.br",
		label = "\\triangle.filled.br  ◢",
		insertText = "◢",
		filterText = "\\triangle.filled.br",
	},
	{
		word = "\\triangle.filled.tl",
		label = "\\triangle.filled.tl  ◤",
		insertText = "◤",
		filterText = "\\triangle.filled.tl",
	},
	{
		word = "\\triangle.filled.tr",
		label = "\\triangle.filled.tr  ◥",
		insertText = "◥",
		filterText = "\\triangle.filled.tr",
	},
	{
		word = "\\triangle.filled.small.t",
		label = "\\triangle.filled.small.t  ▴",
		insertText = "▴",
		filterText = "\\triangle.filled.small.t",
	},
	{
		word = "\\triangle.filled.small.b",
		label = "\\triangle.filled.small.b  ▾",
		insertText = "▾",
		filterText = "\\triangle.filled.small.b",
	},
	{
		word = "\\triangle.filled.small.r",
		label = "\\triangle.filled.small.r  ▸",
		insertText = "▸",
		filterText = "\\triangle.filled.small.r",
	},
	{
		word = "\\triangle.filled.small.l",
		label = "\\triangle.filled.small.l  ◂",
		insertText = "◂",
		filterText = "\\triangle.filled.small.l",
	},
	{ word = "\\square.stroked", label = "\\square.stroked  □", insertText = "□", filterText = "\\square.stroked" },
	{
		word = "\\square.stroked.tiny",
		label = "\\square.stroked.tiny  ▫",
		insertText = "▫",
		filterText = "\\square.stroked.tiny",
	},
	{
		word = "\\square.stroked.small",
		label = "\\square.stroked.small  ◽",
		insertText = "◽",
		filterText = "\\square.stroked.small",
	},
	{
		word = "\\square.stroked.medium",
		label = "\\square.stroked.medium  ◻",
		insertText = "◻",
		filterText = "\\square.stroked.medium",
	},
	{
		word = "\\square.stroked.big",
		label = "\\square.stroked.big  ⬜",
		insertText = "⬜",
		filterText = "\\square.stroked.big",
	},
	{
		word = "\\square.stroked.dotted",
		label = "\\square.stroked.dotted  ⬚",
		insertText = "⬚",
		filterText = "\\square.stroked.dotted",
	},
	{
		word = "\\square.stroked.rounded",
		label = "\\square.stroked.rounded  ▢",
		insertText = "▢",
		filterText = "\\square.stroked.rounded",
	},
	{ word = "\\square.filled", label = "\\square.filled  ■", insertText = "■", filterText = "\\square.filled" },
	{
		word = "\\square.filled.tiny",
		label = "\\square.filled.tiny  ▪",
		insertText = "▪",
		filterText = "\\square.filled.tiny",
	},
	{
		word = "\\square.filled.small",
		label = "\\square.filled.small  ◾",
		insertText = "◾",
		filterText = "\\square.filled.small",
	},
	{
		word = "\\square.filled.medium",
		label = "\\square.filled.medium  ◼",
		insertText = "◼",
		filterText = "\\square.filled.medium",
	},
	{
		word = "\\square.filled.big",
		label = "\\square.filled.big  ⬛",
		insertText = "⬛",
		filterText = "\\square.filled.big",
	},
	{ word = "\\rect.stroked.h", label = "\\rect.stroked.h  ▭", insertText = "▭", filterText = "\\rect.stroked.h" },
	{ word = "\\rect.stroked.v", label = "\\rect.stroked.v  ▯", insertText = "▯", filterText = "\\rect.stroked.v" },
	{ word = "\\rect.filled.h", label = "\\rect.filled.h  ▬", insertText = "▬", filterText = "\\rect.filled.h" },
	{ word = "\\rect.filled.v", label = "\\rect.filled.v  ▮", insertText = "▮", filterText = "\\rect.filled.v" },
	{ word = "\\penta.stroked", label = "\\penta.stroked  ⬠", insertText = "⬠", filterText = "\\penta.stroked" },
	{ word = "\\penta.filled", label = "\\penta.filled  ⬟", insertText = "⬟", filterText = "\\penta.filled" },
	{ word = "\\hexa.stroked", label = "\\hexa.stroked  ⬡", insertText = "⬡", filterText = "\\hexa.stroked" },
	{ word = "\\hexa.filled", label = "\\hexa.filled  ⬢", insertText = "⬢", filterText = "\\hexa.filled" },
	{
		word = "\\diamond.stroked",
		label = "\\diamond.stroked  ◇",
		insertText = "◇",
		filterText = "\\diamond.stroked",
	},
	{
		word = "\\diamond.stroked.small",
		label = "\\diamond.stroked.small  ⋄",
		insertText = "⋄",
		filterText = "\\diamond.stroked.small",
	},
	{
		word = "\\diamond.stroked.medium",
		label = "\\diamond.stroked.medium  ⬦",
		insertText = "⬦",
		filterText = "\\diamond.stroked.medium",
	},
	{
		word = "\\diamond.stroked.dot",
		label = "\\diamond.stroked.dot  ⟐",
		insertText = "⟐",
		filterText = "\\diamond.stroked.dot",
	},
	{ word = "\\diamond.filled", label = "\\diamond.filled  ◆", insertText = "◆", filterText = "\\diamond.filled" },
	{
		word = "\\diamond.filled.medium",
		label = "\\diamond.filled.medium  ⬥",
		insertText = "⬥",
		filterText = "\\diamond.filled.medium",
	},
	{
		word = "\\diamond.filled.small",
		label = "\\diamond.filled.small  ⬩",
		insertText = "⬩",
		filterText = "\\diamond.filled.small",
	},
	{
		word = "\\lozenge.stroked",
		label = "\\lozenge.stroked  ◊",
		insertText = "◊",
		filterText = "\\lozenge.stroked",
	},
	{
		word = "\\lozenge.stroked.small",
		label = "\\lozenge.stroked.small  ⬫",
		insertText = "⬫",
		filterText = "\\lozenge.stroked.small",
	},
	{
		word = "\\lozenge.stroked.medium",
		label = "\\lozenge.stroked.medium  ⬨",
		insertText = "⬨",
		filterText = "\\lozenge.stroked.medium",
	},
	{ word = "\\lozenge.filled", label = "\\lozenge.filled  ⧫", insertText = "⧫", filterText = "\\lozenge.filled" },
	{
		word = "\\lozenge.filled.small",
		label = "\\lozenge.filled.small  ⬪",
		insertText = "⬪",
		filterText = "\\lozenge.filled.small",
	},
	{
		word = "\\lozenge.filled.medium",
		label = "\\lozenge.filled.medium  ⬧",
		insertText = "⬧",
		filterText = "\\lozenge.filled.medium",
	},
	{
		word = "\\parallelogram.stroked",
		label = "\\parallelogram.stroked  ▱",
		insertText = "▱",
		filterText = "\\parallelogram.stroked",
	},
	{
		word = "\\parallelogram.filled",
		label = "\\parallelogram.filled  ▰",
		insertText = "▰",
		filterText = "\\parallelogram.filled",
	},
	{ word = "\\star.op", label = "\\star.op  ⋆", insertText = "⋆", filterText = "\\star.op" },
	{ word = "\\star.stroked", label = "\\star.stroked  ☆", insertText = "☆", filterText = "\\star.stroked" },
	{ word = "\\star.filled", label = "\\star.filled  ★", insertText = "★", filterText = "\\star.filled" },
	{ word = "\\arrow.r", label = "\\arrow.r  →", insertText = "→", filterText = "\\arrow.r" },
	{
		word = "\\arrow.r.long.bar",
		label = "\\arrow.r.long.bar  ⟼",
		insertText = "⟼",
		filterText = "\\arrow.r.long.bar",
	},
	{ word = "\\arrow.r.bar", label = "\\arrow.r.bar  ↦", insertText = "↦", filterText = "\\arrow.r.bar" },
	{ word = "\\arrow.r.curve", label = "\\arrow.r.curve  ⤷", insertText = "⤷", filterText = "\\arrow.r.curve" },
	{ word = "\\arrow.r.turn", label = "\\arrow.r.turn  ⮎", insertText = "⮎", filterText = "\\arrow.r.turn" },
	{ word = "\\arrow.r.dashed", label = "\\arrow.r.dashed  ⇢", insertText = "⇢", filterText = "\\arrow.r.dashed" },
	{ word = "\\arrow.r.dotted", label = "\\arrow.r.dotted  ⤑", insertText = "⤑", filterText = "\\arrow.r.dotted" },
	{ word = "\\arrow.r.double", label = "\\arrow.r.double  ⇒", insertText = "⇒", filterText = "\\arrow.r.double" },
	{
		word = "\\arrow.r.double.bar",
		label = "\\arrow.r.double.bar  ⤇",
		insertText = "⤇",
		filterText = "\\arrow.r.double.bar",
	},
	{
		word = "\\arrow.r.double.long",
		label = "\\arrow.r.double.long  ⟹",
		insertText = "⟹",
		filterText = "\\arrow.r.double.long",
	},
	{
		word = "\\arrow.r.double.long.bar",
		label = "\\arrow.r.double.long.bar  ⟾",
		insertText = "⟾",
		filterText = "\\arrow.r.double.long.bar",
	},
	{
		word = "\\arrow.r.double.not",
		label = "\\arrow.r.double.not  ⇏",
		insertText = "⇏",
		filterText = "\\arrow.r.double.not",
	},
	{ word = "\\arrow.r.filled", label = "\\arrow.r.filled  ➡", insertText = "➡", filterText = "\\arrow.r.filled" },
	{ word = "\\arrow.r.hook", label = "\\arrow.r.hook  ↪", insertText = "↪", filterText = "\\arrow.r.hook" },
	{ word = "\\arrow.r.long", label = "\\arrow.r.long  ⟶", insertText = "⟶", filterText = "\\arrow.r.long" },
	{
		word = "\\arrow.r.long.squiggly",
		label = "\\arrow.r.long.squiggly  ⟿",
		insertText = "⟿",
		filterText = "\\arrow.r.long.squiggly",
	},
	{ word = "\\arrow.r.loop", label = "\\arrow.r.loop  ↬", insertText = "↬", filterText = "\\arrow.r.loop" },
	{ word = "\\arrow.r.not", label = "\\arrow.r.not  ↛", insertText = "↛", filterText = "\\arrow.r.not" },
	{ word = "\\arrow.r.quad", label = "\\arrow.r.quad  ⭆", insertText = "⭆", filterText = "\\arrow.r.quad" },
	{
		word = "\\arrow.r.squiggly",
		label = "\\arrow.r.squiggly  ⇝",
		insertText = "⇝",
		filterText = "\\arrow.r.squiggly",
	},
	{ word = "\\arrow.r.stop", label = "\\arrow.r.stop  ⇥", insertText = "⇥", filterText = "\\arrow.r.stop" },
	{
		word = "\\arrow.r.stroked",
		label = "\\arrow.r.stroked  ⇨",
		insertText = "⇨",
		filterText = "\\arrow.r.stroked",
	},
	{ word = "\\arrow.r.tail", label = "\\arrow.r.tail  ↣", insertText = "↣", filterText = "\\arrow.r.tail" },
	{ word = "\\arrow.r.tilde", label = "\\arrow.r.tilde  ⥲", insertText = "⥲", filterText = "\\arrow.r.tilde" },
	{ word = "\\arrow.r.triple", label = "\\arrow.r.triple  ⇛", insertText = "⇛", filterText = "\\arrow.r.triple" },
	{
		word = "\\arrow.r.twohead.bar",
		label = "\\arrow.r.twohead.bar  ⤅",
		insertText = "⤅",
		filterText = "\\arrow.r.twohead.bar",
	},
	{
		word = "\\arrow.r.twohead",
		label = "\\arrow.r.twohead  ↠",
		insertText = "↠",
		filterText = "\\arrow.r.twohead",
	},
	{ word = "\\arrow.r.wave", label = "\\arrow.r.wave  ↝", insertText = "↝", filterText = "\\arrow.r.wave" },
	{ word = "\\arrow.l", label = "\\arrow.l  ←", insertText = "←", filterText = "\\arrow.l" },
	{ word = "\\arrow.l.bar", label = "\\arrow.l.bar  ↤", insertText = "↤", filterText = "\\arrow.l.bar" },
	{ word = "\\arrow.l.curve", label = "\\arrow.l.curve  ⤶", insertText = "⤶", filterText = "\\arrow.l.curve" },
	{ word = "\\arrow.l.turn", label = "\\arrow.l.turn  ⮌", insertText = "⮌", filterText = "\\arrow.l.turn" },
	{ word = "\\arrow.l.dashed", label = "\\arrow.l.dashed  ⇠", insertText = "⇠", filterText = "\\arrow.l.dashed" },
	{ word = "\\arrow.l.dotted", label = "\\arrow.l.dotted  ⬸", insertText = "⬸", filterText = "\\arrow.l.dotted" },
	{ word = "\\arrow.l.double", label = "\\arrow.l.double  ⇐", insertText = "⇐", filterText = "\\arrow.l.double" },
	{
		word = "\\arrow.l.double.bar",
		label = "\\arrow.l.double.bar  ⤆",
		insertText = "⤆",
		filterText = "\\arrow.l.double.bar",
	},
	{
		word = "\\arrow.l.double.long",
		label = "\\arrow.l.double.long  ⟸",
		insertText = "⟸",
		filterText = "\\arrow.l.double.long",
	},
	{
		word = "\\arrow.l.double.long.bar",
		label = "\\arrow.l.double.long.bar  ⟽",
		insertText = "⟽",
		filterText = "\\arrow.l.double.long.bar",
	},
	{
		word = "\\arrow.l.double.not",
		label = "\\arrow.l.double.not  ⇍",
		insertText = "⇍",
		filterText = "\\arrow.l.double.not",
	},
	{ word = "\\arrow.l.filled", label = "\\arrow.l.filled  ⬅", insertText = "⬅", filterText = "\\arrow.l.filled" },
	{ word = "\\arrow.l.hook", label = "\\arrow.l.hook  ↩", insertText = "↩", filterText = "\\arrow.l.hook" },
	{ word = "\\arrow.l.long", label = "\\arrow.l.long  ⟵", insertText = "⟵", filterText = "\\arrow.l.long" },
	{
		word = "\\arrow.l.long.bar",
		label = "\\arrow.l.long.bar  ⟻",
		insertText = "⟻",
		filterText = "\\arrow.l.long.bar",
	},
	{
		word = "\\arrow.l.long.squiggly",
		label = "\\arrow.l.long.squiggly  ⬳",
		insertText = "⬳",
		filterText = "\\arrow.l.long.squiggly",
	},
	{ word = "\\arrow.l.loop", label = "\\arrow.l.loop  ↫", insertText = "↫", filterText = "\\arrow.l.loop" },
	{ word = "\\arrow.l.not", label = "\\arrow.l.not  ↚", insertText = "↚", filterText = "\\arrow.l.not" },
	{ word = "\\arrow.l.quad", label = "\\arrow.l.quad  ⭅", insertText = "⭅", filterText = "\\arrow.l.quad" },
	{
		word = "\\arrow.l.squiggly",
		label = "\\arrow.l.squiggly  ⇜",
		insertText = "⇜",
		filterText = "\\arrow.l.squiggly",
	},
	{ word = "\\arrow.l.stop", label = "\\arrow.l.stop  ⇤", insertText = "⇤", filterText = "\\arrow.l.stop" },
	{
		word = "\\arrow.l.stroked",
		label = "\\arrow.l.stroked  ⇦",
		insertText = "⇦",
		filterText = "\\arrow.l.stroked",
	},
	{ word = "\\arrow.l.tail", label = "\\arrow.l.tail  ↢", insertText = "↢", filterText = "\\arrow.l.tail" },
	{ word = "\\arrow.l.tilde", label = "\\arrow.l.tilde  ⭉", insertText = "⭉", filterText = "\\arrow.l.tilde" },
	{ word = "\\arrow.l.triple", label = "\\arrow.l.triple  ⇚", insertText = "⇚", filterText = "\\arrow.l.triple" },
	{
		word = "\\arrow.l.twohead.bar",
		label = "\\arrow.l.twohead.bar  ⬶",
		insertText = "⬶",
		filterText = "\\arrow.l.twohead.bar",
	},
	{
		word = "\\arrow.l.twohead",
		label = "\\arrow.l.twohead  ↞",
		insertText = "↞",
		filterText = "\\arrow.l.twohead",
	},
	{ word = "\\arrow.l.wave", label = "\\arrow.l.wave  ↜", insertText = "↜", filterText = "\\arrow.l.wave" },
	{ word = "\\arrow.t", label = "\\arrow.t  ↑", insertText = "↑", filterText = "\\arrow.t" },
	{ word = "\\arrow.t.bar", label = "\\arrow.t.bar  ↥", insertText = "↥", filterText = "\\arrow.t.bar" },
	{ word = "\\arrow.t.curve", label = "\\arrow.t.curve  ⤴", insertText = "⤴", filterText = "\\arrow.t.curve" },
	{ word = "\\arrow.t.turn", label = "\\arrow.t.turn  ⮍", insertText = "⮍", filterText = "\\arrow.t.turn" },
	{ word = "\\arrow.t.dashed", label = "\\arrow.t.dashed  ⇡", insertText = "⇡", filterText = "\\arrow.t.dashed" },
	{ word = "\\arrow.t.double", label = "\\arrow.t.double  ⇑", insertText = "⇑", filterText = "\\arrow.t.double" },
	{ word = "\\arrow.t.filled", label = "\\arrow.t.filled  ⬆", insertText = "⬆", filterText = "\\arrow.t.filled" },
	{ word = "\\arrow.t.quad", label = "\\arrow.t.quad  ⟰", insertText = "⟰", filterText = "\\arrow.t.quad" },
	{ word = "\\arrow.t.stop", label = "\\arrow.t.stop  ⤒", insertText = "⤒", filterText = "\\arrow.t.stop" },
	{
		word = "\\arrow.t.stroked",
		label = "\\arrow.t.stroked  ⇧",
		insertText = "⇧",
		filterText = "\\arrow.t.stroked",
	},
	{ word = "\\arrow.t.triple", label = "\\arrow.t.triple  ⤊", insertText = "⤊", filterText = "\\arrow.t.triple" },
	{
		word = "\\arrow.t.twohead",
		label = "\\arrow.t.twohead  ↟",
		insertText = "↟",
		filterText = "\\arrow.t.twohead",
	},
	{ word = "\\arrow.b", label = "\\arrow.b  ↓", insertText = "↓", filterText = "\\arrow.b" },
	{ word = "\\arrow.b.bar", label = "\\arrow.b.bar  ↧", insertText = "↧", filterText = "\\arrow.b.bar" },
	{ word = "\\arrow.b.curve", label = "\\arrow.b.curve  ⤵", insertText = "⤵", filterText = "\\arrow.b.curve" },
	{ word = "\\arrow.b.turn", label = "\\arrow.b.turn  ⮏", insertText = "⮏", filterText = "\\arrow.b.turn" },
	{ word = "\\arrow.b.dashed", label = "\\arrow.b.dashed  ⇣", insertText = "⇣", filterText = "\\arrow.b.dashed" },
	{ word = "\\arrow.b.double", label = "\\arrow.b.double  ⇓", insertText = "⇓", filterText = "\\arrow.b.double" },
	{ word = "\\arrow.b.filled", label = "\\arrow.b.filled  ⬇", insertText = "⬇", filterText = "\\arrow.b.filled" },
	{ word = "\\arrow.b.quad", label = "\\arrow.b.quad  ⟱", insertText = "⟱", filterText = "\\arrow.b.quad" },
	{ word = "\\arrow.b.stop", label = "\\arrow.b.stop  ⤓", insertText = "⤓", filterText = "\\arrow.b.stop" },
	{
		word = "\\arrow.b.stroked",
		label = "\\arrow.b.stroked  ⇩",
		insertText = "⇩",
		filterText = "\\arrow.b.stroked",
	},
	{ word = "\\arrow.b.triple", label = "\\arrow.b.triple  ⤋", insertText = "⤋", filterText = "\\arrow.b.triple" },
	{
		word = "\\arrow.b.twohead",
		label = "\\arrow.b.twohead  ↡",
		insertText = "↡",
		filterText = "\\arrow.b.twohead",
	},
	{ word = "\\arrow.l.r", label = "\\arrow.l.r  ↔", insertText = "↔", filterText = "\\arrow.l.r" },
	{
		word = "\\arrow.l.r.double",
		label = "\\arrow.l.r.double  ⇔",
		insertText = "⇔",
		filterText = "\\arrow.l.r.double",
	},
	{
		word = "\\arrow.l.r.double.long",
		label = "\\arrow.l.r.double.long  ⟺",
		insertText = "⟺",
		filterText = "\\arrow.l.r.double.long",
	},
	{
		word = "\\arrow.l.r.double.not",
		label = "\\arrow.l.r.double.not  ⇎",
		insertText = "⇎",
		filterText = "\\arrow.l.r.double.not",
	},
	{
		word = "\\arrow.l.r.filled",
		label = "\\arrow.l.r.filled  ⬌",
		insertText = "⬌",
		filterText = "\\arrow.l.r.filled",
	},
	{ word = "\\arrow.l.r.long", label = "\\arrow.l.r.long  ⟷", insertText = "⟷", filterText = "\\arrow.l.r.long" },
	{ word = "\\arrow.l.r.not", label = "\\arrow.l.r.not  ↮", insertText = "↮", filterText = "\\arrow.l.r.not" },
	{
		word = "\\arrow.l.r.stroked",
		label = "\\arrow.l.r.stroked  ⬄",
		insertText = "⬄",
		filterText = "\\arrow.l.r.stroked",
	},
	{ word = "\\arrow.l.r.wave", label = "\\arrow.l.r.wave  ↭", insertText = "↭", filterText = "\\arrow.l.r.wave" },
	{ word = "\\arrow.t.b", label = "\\arrow.t.b  ↕", insertText = "↕", filterText = "\\arrow.t.b" },
	{
		word = "\\arrow.t.b.double",
		label = "\\arrow.t.b.double  ⇕",
		insertText = "⇕",
		filterText = "\\arrow.t.b.double",
	},
	{
		word = "\\arrow.t.b.filled",
		label = "\\arrow.t.b.filled  ⬍",
		insertText = "⬍",
		filterText = "\\arrow.t.b.filled",
	},
	{
		word = "\\arrow.t.b.stroked",
		label = "\\arrow.t.b.stroked  ⇳",
		insertText = "⇳",
		filterText = "\\arrow.t.b.stroked",
	},
	{ word = "\\arrow.tr", label = "\\arrow.tr  ↗", insertText = "↗", filterText = "\\arrow.tr" },
	{
		word = "\\arrow.tr.double",
		label = "\\arrow.tr.double  ⇗",
		insertText = "⇗",
		filterText = "\\arrow.tr.double",
	},
	{
		word = "\\arrow.tr.filled",
		label = "\\arrow.tr.filled  ⬈",
		insertText = "⬈",
		filterText = "\\arrow.tr.filled",
	},
	{ word = "\\arrow.tr.hook", label = "\\arrow.tr.hook  ⤤", insertText = "⤤", filterText = "\\arrow.tr.hook" },
	{
		word = "\\arrow.tr.stroked",
		label = "\\arrow.tr.stroked  ⬀",
		insertText = "⬀",
		filterText = "\\arrow.tr.stroked",
	},
	{ word = "\\arrow.br", label = "\\arrow.br  ↘", insertText = "↘", filterText = "\\arrow.br" },
	{
		word = "\\arrow.br.double",
		label = "\\arrow.br.double  ⇘",
		insertText = "⇘",
		filterText = "\\arrow.br.double",
	},
	{
		word = "\\arrow.br.filled",
		label = "\\arrow.br.filled  ⬊",
		insertText = "⬊",
		filterText = "\\arrow.br.filled",
	},
	{ word = "\\arrow.br.hook", label = "\\arrow.br.hook  ⤥", insertText = "⤥", filterText = "\\arrow.br.hook" },
	{
		word = "\\arrow.br.stroked",
		label = "\\arrow.br.stroked  ⬂",
		insertText = "⬂",
		filterText = "\\arrow.br.stroked",
	},
	{ word = "\\arrow.tl", label = "\\arrow.tl  ↖", insertText = "↖", filterText = "\\arrow.tl" },
	{
		word = "\\arrow.tl.double",
		label = "\\arrow.tl.double  ⇖",
		insertText = "⇖",
		filterText = "\\arrow.tl.double",
	},
	{
		word = "\\arrow.tl.filled",
		label = "\\arrow.tl.filled  ⬉",
		insertText = "⬉",
		filterText = "\\arrow.tl.filled",
	},
	{ word = "\\arrow.tl.hook", label = "\\arrow.tl.hook  ⤣", insertText = "⤣", filterText = "\\arrow.tl.hook" },
	{
		word = "\\arrow.tl.stroked",
		label = "\\arrow.tl.stroked  ⬁",
		insertText = "⬁",
		filterText = "\\arrow.tl.stroked",
	},
	{ word = "\\arrow.bl", label = "\\arrow.bl  ↙", insertText = "↙", filterText = "\\arrow.bl" },
	{
		word = "\\arrow.bl.double",
		label = "\\arrow.bl.double  ⇙",
		insertText = "⇙",
		filterText = "\\arrow.bl.double",
	},
	{
		word = "\\arrow.bl.filled",
		label = "\\arrow.bl.filled  ⬋",
		insertText = "⬋",
		filterText = "\\arrow.bl.filled",
	},
	{ word = "\\arrow.bl.hook", label = "\\arrow.bl.hook  ⤦", insertText = "⤦", filterText = "\\arrow.bl.hook" },
	{
		word = "\\arrow.bl.stroked",
		label = "\\arrow.bl.stroked  ⬃",
		insertText = "⬃",
		filterText = "\\arrow.bl.stroked",
	},
	{ word = "\\arrow.tl.br", label = "\\arrow.tl.br  ⤡", insertText = "⤡", filterText = "\\arrow.tl.br" },
	{ word = "\\arrow.tr.bl", label = "\\arrow.tr.bl  ⤢", insertText = "⤢", filterText = "\\arrow.tr.bl" },
	{ word = "\\arrow.ccw", label = "\\arrow.ccw  ↺", insertText = "↺", filterText = "\\arrow.ccw" },
	{ word = "\\arrow.ccw.half", label = "\\arrow.ccw.half  ↶", insertText = "↶", filterText = "\\arrow.ccw.half" },
	{ word = "\\arrow.cw", label = "\\arrow.cw  ↻", insertText = "↻", filterText = "\\arrow.cw" },
	{ word = "\\arrow.cw.half", label = "\\arrow.cw.half  ↷", insertText = "↷", filterText = "\\arrow.cw.half" },
	{ word = "\\arrow.zigzag", label = "\\arrow.zigzag  ↯", insertText = "↯", filterText = "\\arrow.zigzag" },
	{ word = "\\arrows.rr", label = "\\arrows.rr  ⇉", insertText = "⇉", filterText = "\\arrows.rr" },
	{ word = "\\arrows.ll", label = "\\arrows.ll  ⇇", insertText = "⇇", filterText = "\\arrows.ll" },
	{ word = "\\arrows.tt", label = "\\arrows.tt  ⇈", insertText = "⇈", filterText = "\\arrows.tt" },
	{ word = "\\arrows.bb", label = "\\arrows.bb  ⇊", insertText = "⇊", filterText = "\\arrows.bb" },
	{ word = "\\arrows.lr", label = "\\arrows.lr  ⇆", insertText = "⇆", filterText = "\\arrows.lr" },
	{ word = "\\arrows.lr.stop", label = "\\arrows.lr.stop  ↹", insertText = "↹", filterText = "\\arrows.lr.stop" },
	{ word = "\\arrows.rl", label = "\\arrows.rl  ⇄", insertText = "⇄", filterText = "\\arrows.rl" },
	{ word = "\\arrows.tb", label = "\\arrows.tb  ⇅", insertText = "⇅", filterText = "\\arrows.tb" },
	{ word = "\\arrows.bt", label = "\\arrows.bt  ⇵", insertText = "⇵", filterText = "\\arrows.bt" },
	{ word = "\\arrows.rrr", label = "\\arrows.rrr  ⇶", insertText = "⇶", filterText = "\\arrows.rrr" },
	{ word = "\\arrows.lll", label = "\\arrows.lll  ⬱", insertText = "⬱", filterText = "\\arrows.lll" },
	{ word = "\\arrowhead.t", label = "\\arrowhead.t  ⌃", insertText = "⌃", filterText = "\\arrowhead.t" },
	{ word = "\\arrowhead.b", label = "\\arrowhead.b  ⌄", insertText = "⌄", filterText = "\\arrowhead.b" },
	{ word = "\\harpoon.rt", label = "\\harpoon.rt  ⇀", insertText = "⇀", filterText = "\\harpoon.rt" },
	{ word = "\\harpoon.rt.bar", label = "\\harpoon.rt.bar  ⥛", insertText = "⥛", filterText = "\\harpoon.rt.bar" },
	{
		word = "\\harpoon.rt.stop",
		label = "\\harpoon.rt.stop  ⥓",
		insertText = "⥓",
		filterText = "\\harpoon.rt.stop",
	},
	{ word = "\\harpoon.rb", label = "\\harpoon.rb  ⇁", insertText = "⇁", filterText = "\\harpoon.rb" },
	{ word = "\\harpoon.rb.bar", label = "\\harpoon.rb.bar  ⥟", insertText = "⥟", filterText = "\\harpoon.rb.bar" },
	{
		word = "\\harpoon.rb.stop",
		label = "\\harpoon.rb.stop  ⥗",
		insertText = "⥗",
		filterText = "\\harpoon.rb.stop",
	},
	{ word = "\\harpoon.lt", label = "\\harpoon.lt  ↼", insertText = "↼", filterText = "\\harpoon.lt" },
	{ word = "\\harpoon.lt.bar", label = "\\harpoon.lt.bar  ⥚", insertText = "⥚", filterText = "\\harpoon.lt.bar" },
	{
		word = "\\harpoon.lt.stop",
		label = "\\harpoon.lt.stop  ⥒",
		insertText = "⥒",
		filterText = "\\harpoon.lt.stop",
	},
	{ word = "\\harpoon.lb", label = "\\harpoon.lb  ↽", insertText = "↽", filterText = "\\harpoon.lb" },
	{ word = "\\harpoon.lb.bar", label = "\\harpoon.lb.bar  ⥞", insertText = "⥞", filterText = "\\harpoon.lb.bar" },
	{
		word = "\\harpoon.lb.stop",
		label = "\\harpoon.lb.stop  ⥖",
		insertText = "⥖",
		filterText = "\\harpoon.lb.stop",
	},
	{ word = "\\harpoon.tl", label = "\\harpoon.tl  ↿", insertText = "↿", filterText = "\\harpoon.tl" },
	{ word = "\\harpoon.tl.bar", label = "\\harpoon.tl.bar  ⥠", insertText = "⥠", filterText = "\\harpoon.tl.bar" },
	{
		word = "\\harpoon.tl.stop",
		label = "\\harpoon.tl.stop  ⥘",
		insertText = "⥘",
		filterText = "\\harpoon.tl.stop",
	},
	{ word = "\\harpoon.tr", label = "\\harpoon.tr  ↾", insertText = "↾", filterText = "\\harpoon.tr" },
	{ word = "\\harpoon.tr.bar", label = "\\harpoon.tr.bar  ⥜", insertText = "⥜", filterText = "\\harpoon.tr.bar" },
	{
		word = "\\harpoon.tr.stop",
		label = "\\harpoon.tr.stop  ⥔",
		insertText = "⥔",
		filterText = "\\harpoon.tr.stop",
	},
	{ word = "\\harpoon.bl", label = "\\harpoon.bl  ⇃", insertText = "⇃", filterText = "\\harpoon.bl" },
	{ word = "\\harpoon.bl.bar", label = "\\harpoon.bl.bar  ⥡", insertText = "⥡", filterText = "\\harpoon.bl.bar" },
	{
		word = "\\harpoon.bl.stop",
		label = "\\harpoon.bl.stop  ⥙",
		insertText = "⥙",
		filterText = "\\harpoon.bl.stop",
	},
	{ word = "\\harpoon.br", label = "\\harpoon.br  ⇂", insertText = "⇂", filterText = "\\harpoon.br" },
	{ word = "\\harpoon.br.bar", label = "\\harpoon.br.bar  ⥝", insertText = "⥝", filterText = "\\harpoon.br.bar" },
	{
		word = "\\harpoon.br.stop",
		label = "\\harpoon.br.stop  ⥕",
		insertText = "⥕",
		filterText = "\\harpoon.br.stop",
	},
	{ word = "\\harpoon.lt.rt", label = "\\harpoon.lt.rt  ⥎", insertText = "⥎", filterText = "\\harpoon.lt.rt" },
	{ word = "\\harpoon.lb.rb", label = "\\harpoon.lb.rb  ⥐", insertText = "⥐", filterText = "\\harpoon.lb.rb" },
	{ word = "\\harpoon.lb.rt", label = "\\harpoon.lb.rt  ⥋", insertText = "⥋", filterText = "\\harpoon.lb.rt" },
	{ word = "\\harpoon.lt.rb", label = "\\harpoon.lt.rb  ⥊", insertText = "⥊", filterText = "\\harpoon.lt.rb" },
	{ word = "\\harpoon.tl.bl", label = "\\harpoon.tl.bl  ⥑", insertText = "⥑", filterText = "\\harpoon.tl.bl" },
	{ word = "\\harpoon.tr.br", label = "\\harpoon.tr.br  ⥏", insertText = "⥏", filterText = "\\harpoon.tr.br" },
	{ word = "\\harpoon.tl.br", label = "\\harpoon.tl.br  ⥍", insertText = "⥍", filterText = "\\harpoon.tl.br" },
	{ word = "\\harpoon.tr.bl", label = "\\harpoon.tr.bl  ⥌", insertText = "⥌", filterText = "\\harpoon.tr.bl" },
	{ word = "\\harpoons.rtrb", label = "\\harpoons.rtrb  ⥤", insertText = "⥤", filterText = "\\harpoons.rtrb" },
	{ word = "\\harpoons.blbr", label = "\\harpoons.blbr  ⥥", insertText = "⥥", filterText = "\\harpoons.blbr" },
	{ word = "\\harpoons.bltr", label = "\\harpoons.bltr  ⥯", insertText = "⥯", filterText = "\\harpoons.bltr" },
	{ word = "\\harpoons.lbrb", label = "\\harpoons.lbrb  ⥧", insertText = "⥧", filterText = "\\harpoons.lbrb" },
	{ word = "\\harpoons.ltlb", label = "\\harpoons.ltlb  ⥢", insertText = "⥢", filterText = "\\harpoons.ltlb" },
	{ word = "\\harpoons.ltrb", label = "\\harpoons.ltrb  ⇋", insertText = "⇋", filterText = "\\harpoons.ltrb" },
	{ word = "\\harpoons.ltrt", label = "\\harpoons.ltrt  ⥦", insertText = "⥦", filterText = "\\harpoons.ltrt" },
	{ word = "\\harpoons.rblb", label = "\\harpoons.rblb  ⥩", insertText = "⥩", filterText = "\\harpoons.rblb" },
	{ word = "\\harpoons.rtlb", label = "\\harpoons.rtlb  ⇌", insertText = "⇌", filterText = "\\harpoons.rtlb" },
	{ word = "\\harpoons.rtlt", label = "\\harpoons.rtlt  ⥨", insertText = "⥨", filterText = "\\harpoons.rtlt" },
	{ word = "\\harpoons.tlbr", label = "\\harpoons.tlbr  ⥮", insertText = "⥮", filterText = "\\harpoons.tlbr" },
	{ word = "\\harpoons.tltr", label = "\\harpoons.tltr  ⥣", insertText = "⥣", filterText = "\\harpoons.tltr" },
	{ word = "\\tack.r", label = "\\tack.r  ⊢", insertText = "⊢", filterText = "\\tack.r" },
	{ word = "\\tack.r.not", label = "\\tack.r.not  ⊬", insertText = "⊬", filterText = "\\tack.r.not" },
	{ word = "\\tack.r.long", label = "\\tack.r.long  ⟝", insertText = "⟝", filterText = "\\tack.r.long" },
	{ word = "\\tack.r.short", label = "\\tack.r.short  ⊦", insertText = "⊦", filterText = "\\tack.r.short" },
	{ word = "\\tack.r.double", label = "\\tack.r.double  ⊨", insertText = "⊨", filterText = "\\tack.r.double" },
	{
		word = "\\tack.r.double.not",
		label = "\\tack.r.double.not  ⊭",
		insertText = "⊭",
		filterText = "\\tack.r.double.not",
	},
	{ word = "\\tack.l", label = "\\tack.l  ⊣", insertText = "⊣", filterText = "\\tack.l" },
	{ word = "\\tack.l.long", label = "\\tack.l.long  ⟞", insertText = "⟞", filterText = "\\tack.l.long" },
	{ word = "\\tack.l.short", label = "\\tack.l.short  ⫞", insertText = "⫞", filterText = "\\tack.l.short" },
	{ word = "\\tack.l.double", label = "\\tack.l.double  ⫤", insertText = "⫤", filterText = "\\tack.l.double" },
	{ word = "\\tack.t", label = "\\tack.t  ⊥", insertText = "⊥", filterText = "\\tack.t" },
	{ word = "\\tack.t.big", label = "\\tack.t.big  ⟘", insertText = "⟘", filterText = "\\tack.t.big" },
	{ word = "\\tack.t.double", label = "\\tack.t.double  ⫫", insertText = "⫫", filterText = "\\tack.t.double" },
	{ word = "\\tack.t.short", label = "\\tack.t.short  ⫠", insertText = "⫠", filterText = "\\tack.t.short" },
	{ word = "\\tack.b", label = "\\tack.b  ⊤", insertText = "⊤", filterText = "\\tack.b" },
	{ word = "\\tack.b.big", label = "\\tack.b.big  ⟙", insertText = "⟙", filterText = "\\tack.b.big" },
	{ word = "\\tack.b.double", label = "\\tack.b.double  ⫪", insertText = "⫪", filterText = "\\tack.b.double" },
	{ word = "\\tack.b.short", label = "\\tack.b.short  ⫟", insertText = "⫟", filterText = "\\tack.b.short" },
	{ word = "\\tack.l.r", label = "\\tack.l.r  ⟛", insertText = "⟛", filterText = "\\tack.l.r" },
	{ word = "\\alpha.", label = "\\alpha.  α", insertText = "α", filterText = "\\alpha." },
	{ word = "\\beta.", label = "\\beta.  β", insertText = "β", filterText = "\\beta." },
	{ word = "\\beta.alt", label = "\\beta.alt  ϐ", insertText = "ϐ", filterText = "\\beta.alt" },
	{ word = "\\chi.", label = "\\chi.  χ", insertText = "χ", filterText = "\\chi." },
	{ word = "\\delta.", label = "\\delta.  δ", insertText = "δ", filterText = "\\delta." },
	{ word = "\\epsilon.", label = "\\epsilon.  ε", insertText = "ε", filterText = "\\epsilon." },
	{ word = "\\epsilon.alt", label = "\\epsilon.alt  ϵ", insertText = "ϵ", filterText = "\\epsilon.alt" },
	{ word = "\\eta.", label = "\\eta.  η", insertText = "η", filterText = "\\eta." },
	{ word = "\\gamma.", label = "\\gamma.  γ", insertText = "γ", filterText = "\\gamma." },
	{ word = "\\iota.", label = "\\iota.  ι", insertText = "ι", filterText = "\\iota." },
	{ word = "\\kai.", label = "\\kai.  ϗ", insertText = "ϗ", filterText = "\\kai." },
	{ word = "\\kappa.", label = "\\kappa.  κ", insertText = "κ", filterText = "\\kappa." },
	{ word = "\\kappa.alt", label = "\\kappa.alt  ϰ", insertText = "ϰ", filterText = "\\kappa.alt" },
	{ word = "\\lambda.", label = "\\lambda.  λ", insertText = "λ", filterText = "\\lambda." },
	{ word = "\\mu.", label = "\\mu.  μ", insertText = "μ", filterText = "\\mu." },
	{ word = "\\nu.", label = "\\nu.  ν", insertText = "ν", filterText = "\\nu." },
	{ word = "\\ohm.", label = "\\ohm.  Ω", insertText = "Ω", filterText = "\\ohm." },
	{ word = "\\ohm.inv", label = "\\ohm.inv  ℧", insertText = "℧", filterText = "\\ohm.inv" },
	{ word = "\\omega.", label = "\\omega.  ω", insertText = "ω", filterText = "\\omega." },
	{ word = "\\omicron.", label = "\\omicron.  ο", insertText = "ο", filterText = "\\omicron." },
	{ word = "\\phi.", label = "\\phi.  φ", insertText = "φ", filterText = "\\phi." },
	{ word = "\\phi.alt", label = "\\phi.alt  ϕ", insertText = "ϕ", filterText = "\\phi.alt" },
	{ word = "\\pi.", label = "\\pi.  π", insertText = "π", filterText = "\\pi." },
	{ word = "\\pi.alt", label = "\\pi.alt  ϖ", insertText = "ϖ", filterText = "\\pi.alt" },
	{ word = "\\psi.", label = "\\psi.  ψ", insertText = "ψ", filterText = "\\psi." },
	{ word = "\\rho.", label = "\\rho.  ρ", insertText = "ρ", filterText = "\\rho." },
	{ word = "\\rho.alt", label = "\\rho.alt  ϱ", insertText = "ϱ", filterText = "\\rho.alt" },
	{ word = "\\sigma.", label = "\\sigma.  σ", insertText = "σ", filterText = "\\sigma." },
	{ word = "\\sigma.alt", label = "\\sigma.alt  ς", insertText = "ς", filterText = "\\sigma.alt" },
	{ word = "\\tau.", label = "\\tau.  τ", insertText = "τ", filterText = "\\tau." },
	{ word = "\\theta.", label = "\\theta.  θ", insertText = "θ", filterText = "\\theta." },
	{ word = "\\theta.alt", label = "\\theta.alt  ϑ", insertText = "ϑ", filterText = "\\theta.alt" },
	{ word = "\\upsilon.", label = "\\upsilon.  υ", insertText = "υ", filterText = "\\upsilon." },
	{ word = "\\xi.", label = "\\xi.  ξ", insertText = "ξ", filterText = "\\xi." },
	{ word = "\\zeta.", label = "\\zeta.  ζ", insertText = "ζ", filterText = "\\zeta." },
	{ word = "\\Alpha.", label = "\\Alpha.  Α", insertText = "Α", filterText = "\\Alpha." },
	{ word = "\\Beta.", label = "\\Beta.  Β", insertText = "Β", filterText = "\\Beta." },
	{ word = "\\Chi.", label = "\\Chi.  Χ", insertText = "Χ", filterText = "\\Chi." },
	{ word = "\\Delta.", label = "\\Delta.  Δ", insertText = "Δ", filterText = "\\Delta." },
	{ word = "\\Epsilon.", label = "\\Epsilon.  Ε", insertText = "Ε", filterText = "\\Epsilon." },
	{ word = "\\Eta.", label = "\\Eta.  Η", insertText = "Η", filterText = "\\Eta." },
	{ word = "\\Gamma.", label = "\\Gamma.  Γ", insertText = "Γ", filterText = "\\Gamma." },
	{ word = "\\Iota.", label = "\\Iota.  Ι", insertText = "Ι", filterText = "\\Iota." },
	{ word = "\\Kai.", label = "\\Kai.  Ϗ", insertText = "Ϗ", filterText = "\\Kai." },
	{ word = "\\Kappa.", label = "\\Kappa.  Κ", insertText = "Κ", filterText = "\\Kappa." },
	{ word = "\\Lambda.", label = "\\Lambda.  Λ", insertText = "Λ", filterText = "\\Lambda." },
	{ word = "\\Mu.", label = "\\Mu.  Μ", insertText = "Μ", filterText = "\\Mu." },
	{ word = "\\Nu.", label = "\\Nu.  Ν", insertText = "Ν", filterText = "\\Nu." },
	{ word = "\\Omega.", label = "\\Omega.  Ω", insertText = "Ω", filterText = "\\Omega." },
	{ word = "\\Omicron.", label = "\\Omicron.  Ο", insertText = "Ο", filterText = "\\Omicron." },
	{ word = "\\Phi.", label = "\\Phi.  Φ", insertText = "Φ", filterText = "\\Phi." },
	{ word = "\\Pi.", label = "\\Pi.  Π", insertText = "Π", filterText = "\\Pi." },
	{ word = "\\Psi.", label = "\\Psi.  Ψ", insertText = "Ψ", filterText = "\\Psi." },
	{ word = "\\Rho.", label = "\\Rho.  Ρ", insertText = "Ρ", filterText = "\\Rho." },
	{ word = "\\Sigma.", label = "\\Sigma.  Σ", insertText = "Σ", filterText = "\\Sigma." },
	{ word = "\\Tau.", label = "\\Tau.  Τ", insertText = "Τ", filterText = "\\Tau." },
	{ word = "\\Theta.", label = "\\Theta.  Θ", insertText = "Θ", filterText = "\\Theta." },
	{ word = "\\Upsilon.", label = "\\Upsilon.  Υ", insertText = "Υ", filterText = "\\Upsilon." },
	{ word = "\\Xi.", label = "\\Xi.  Ξ", insertText = "Ξ", filterText = "\\Xi." },
	{ word = "\\Zeta.", label = "\\Zeta.  Ζ", insertText = "Ζ", filterText = "\\Zeta." },
	{ word = "\\aleph.", label = "\\aleph.  א", insertText = "א", filterText = "\\aleph." },
	{ word = "\\alef.", label = "\\alef.  א", insertText = "א", filterText = "\\alef." },
	{ word = "\\beth.", label = "\\beth.  ב", insertText = "ב", filterText = "\\beth." },
	{ word = "\\bet.", label = "\\bet.  ב", insertText = "ב", filterText = "\\bet." },
	{ word = "\\gimmel.", label = "\\gimmel.  ג", insertText = "ג", filterText = "\\gimmel." },
	{ word = "\\gimel.", label = "\\gimel.  ג", insertText = "ג", filterText = "\\gimel." },
	{ word = "\\daleth.", label = "\\daleth.  ד", insertText = "ד", filterText = "\\daleth." },
	{ word = "\\dalet.", label = "\\dalet.  ד", insertText = "ד", filterText = "\\dalet." },
	{ word = "\\shin.", label = "\\shin.  ש", insertText = "ש", filterText = "\\shin." },
	{ word = "\\AA.", label = "\\AA.  𝔸", insertText = "𝔸", filterText = "\\AA." },
	{ word = "\\BB.", label = "\\BB.  𝔹", insertText = "𝔹", filterText = "\\BB." },
	{ word = "\\CC.", label = "\\CC.  ℂ", insertText = "ℂ", filterText = "\\CC." },
	{ word = "\\DD.", label = "\\DD.  𝔻", insertText = "𝔻", filterText = "\\DD." },
	{ word = "\\EE.", label = "\\EE.  𝔼", insertText = "𝔼", filterText = "\\EE." },
	{ word = "\\FF.", label = "\\FF.  𝔽", insertText = "𝔽", filterText = "\\FF." },
	{ word = "\\GG.", label = "\\GG.  𝔾", insertText = "𝔾", filterText = "\\GG." },
	{ word = "\\HH.", label = "\\HH.  ℍ", insertText = "ℍ", filterText = "\\HH." },
	{ word = "\\II.", label = "\\II.  𝕀", insertText = "𝕀", filterText = "\\II." },
	{ word = "\\JJ.", label = "\\JJ.  𝕁", insertText = "𝕁", filterText = "\\JJ." },
	{ word = "\\KK.", label = "\\KK.  𝕂", insertText = "𝕂", filterText = "\\KK." },
	{ word = "\\LL.", label = "\\LL.  𝕃", insertText = "𝕃", filterText = "\\LL." },
	{ word = "\\MM.", label = "\\MM.  𝕄", insertText = "𝕄", filterText = "\\MM." },
	{ word = "\\NN.", label = "\\NN.  ℕ", insertText = "ℕ", filterText = "\\NN." },
	{ word = "\\OO.", label = "\\OO.  𝕆", insertText = "𝕆", filterText = "\\OO." },
	{ word = "\\PP.", label = "\\PP.  ℙ", insertText = "ℙ", filterText = "\\PP." },
	{ word = "\\QQ.", label = "\\QQ.  ℚ", insertText = "ℚ", filterText = "\\QQ." },
	{ word = "\\RR.", label = "\\RR.  ℝ", insertText = "ℝ", filterText = "\\RR." },
	{ word = "\\SS.", label = "\\SS.  𝕊", insertText = "𝕊", filterText = "\\SS." },
	{ word = "\\TT.", label = "\\TT.  𝕋", insertText = "𝕋", filterText = "\\TT." },
	{ word = "\\UU.", label = "\\UU.  𝕌", insertText = "𝕌", filterText = "\\UU." },
	{ word = "\\VV.", label = "\\VV.  𝕍", insertText = "𝕍", filterText = "\\VV." },
	{ word = "\\WW.", label = "\\WW.  𝕎", insertText = "𝕎", filterText = "\\WW." },
	{ word = "\\XX.", label = "\\XX.  𝕏", insertText = "𝕏", filterText = "\\XX." },
	{ word = "\\YY.", label = "\\YY.  𝕐", insertText = "𝕐", filterText = "\\YY." },
	{ word = "\\ZZ.", label = "\\ZZ.  ℤ", insertText = "ℤ", filterText = "\\ZZ." },
	{ word = "\\ell.", label = "\\ell.  ℓ", insertText = "ℓ", filterText = "\\ell." },
	{ word = "\\planck.", label = "\\planck.  ℎ", insertText = "ℎ", filterText = "\\planck." },
	{ word = "\\planck.reduce", label = "\\planck.reduce  ℏ", insertText = "ℏ", filterText = "\\planck.reduce" },
	{ word = "\\angstrom.", label = "\\angstrom.  Å", insertText = "Å", filterText = "\\angstrom." },
	{ word = "\\kelvin.", label = "\\kelvin.  K", insertText = "K", filterText = "\\kelvin." },
	{ word = "\\Re.", label = "\\Re.  ℜ", insertText = "ℜ", filterText = "\\Re." },
	{ word = "\\Im.", label = "\\Im.  ℑ", insertText = "ℑ", filterText = "\\Im." },
	{ word = "\\dotless.i", label = "\\dotless.i  𝚤", insertText = "𝚤", filterText = "\\dotless.i" },
	{ word = "\\dotless.j", label = "\\dotless.j  𝚥", insertText = "𝚥", filterText = "\\dotless.j" },
}
